Repository shellhub-io/shellhub, pull requests merged in 2020-06, with the labels that each got.

#153 Ignore *.orig files
  .gitignore
  api/pkg/store/mongo/store.go.orig
Labels: :mag: Needs Review

#154 api: move filter query builder to a func to make code more readable
  api/pkg/store/mongo/store.go
Labels: :mag: Needs Review

#156 api: move common pagination query builder to a function
  api/pkg/store/mongo/store.go
Labels: :mag: Needs Review

#158 pkg: move filter model to a separate file
  pkg/models/device.go
  pkg/models/filter.go
Labels: :mag: Needs Review

#163 cicd: add unit test step in javascript workflow
  .github/workflows/javascript.yml
Labels: :mag: Needs Review

#164 ui: Formatting dialogs and display
  ui/src/components/device/DeviceDelete.vue
  ui/src/components/device/DeviceDetails.vue
  ui/src/components/device/DeviceRename.vue
  ui/src/components/session/SessionDetails.vue
  ui/src/components/terminal/TerminalDialog.vue
  ui/src/views/Dashboard.vue
Labels: :mag: Needs Review

#181 ui: Update xtermjs 3.14.5 -> 4.7.0
  ui/package-lock.json
  ui/package.json
  ui/src/components/terminal/TerminalDialog.vue
Labels: :heavy_check_mark: Good to Merge

#188 api: firewall rules
  api/main.go
  api/pkg/services/firewall/service.go
  api/pkg/store/mongo/store.go
  api/pkg/store/store.go
  pkg/models/firewall.go
  ssh/go.mod
  ssh/go.sum
  ssh/session.go
Labels: :mag: Needs Review

#194 Feature/firewall rules ui
  ui/src/App.vue
  ui/src/api/firewall_rules.js
  ui/src/components/firewall_rules/FirewallRulesDelete.vue
  ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
  ui/src/components/firewall_rules/FirewallRulesList.vue
  ui/src/modules/firewall_rules.js
  ui/src/router/index.js
  ui/src/store.js
  ui/src/views/FirewallRules.vue
Labels: :construction: Work in Progress, :no_entry: DO NOT MERGE
