Repository shellhub-io/shellhub, pull requests merged in 2021-04, with the labels that each got.

#837 ui: Resolve erros in console and fix show instructions namespace
  ui/src/components/app_bar/AppBar.vue
  ui/src/components/app_bar/namespace/NamespaceInstructions.vue
  ui/src/components/app_bar/namespace/NamespaceMenu.vue
  ui/src/components/app_bar/notification/Notification.vue
  ui/src/store/modules/namespaces.js
  ui/src/views/Dashboard.vue
Labels: area/ui

#838 gateway: add some tunning to nginx config
  gateway/entrypoint.sh
  gateway/nginx.conf
Labels: area/docker

#847 ui: add snackbar incorrect in login
  ui/src/components/snackbar/SnackbarError.vue
  ui/src/errors.js
  ui/src/store/helpers/http.js
  ui/src/store/modules/auth.js
  ui/src/store/modules/snackbar.js
  ui/src/views/Login.vue
  ui/tests/unit/store/Snackbar.spec.js
Labels: area/ui

#848 cicd: add missing go dependencies
  go.mod
Labels: area/ci-cd

#844 ui: fix on delete namespace errors
  ui/src/components/app_bar/namespace/NamespaceDelete.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/src/components/setting/SettingSecurity.vue
  ui/tests/unit/components/setting/SettingNamespace.spec.js
Labels: area/ui

#856 ui: add support message for valid key types
  ui/src/components/public_key/KeyFormDialog.vue
Labels: area/ui

#855 api: fix firewall rule id to use ObjectId
  api/store/mongo/firewall_store.go
  api/store/mongo/migrations.go
  pkg/models/firewall.go
Labels: area/api, status/needs-review

#860 ui: Add support hotjar
  ui/package-lock.json
  ui/package.json
  ui/src/main.js
Labels: area/ui

#863 cicd: update workflow for buildx
  .github/workflows/build-agent.yml
Labels: area/ci-cd

#865 agent: update go modules
  agent/go.mod
  agent/go.sum
Labels: area/agent

#864 api: Add pagination support when export csv
  api/store/mongo/namespace_store.go
Labels: area/api

#823 api-cli: Added new package cli for api
  .github/workflows/docker-build.yml
  .github/workflows/docker-publish.yml
  .github/workflows/qa.yml
  .gitignore
  bin/add-namespace
  bin/add-user
  bin/add-user-namespace
  bin/del-namespace
  bin/del-user
  bin/del-user-namespace
  bin/reset-user-password
  cli/Dockerfile
  cli/entrypoint-dev.sh
  cli/entrypoint.sh
  cli/go.mod
  cli/go.sum
  cli/main.go
  cli/refresh.yml
  cli/service.go
  cli/service_test.go
  docker-compose.dev.yml
  docker-compose.yml
  go.mod
Labels: area/api, status/changes-requested

#874 ui: Fix unit test in namespace setting
  ui/tests/unit/components/setting/SettingNamespace.spec.js
Labels: area/ui

#877 ui: Set sass loader version less than 11
  ui/package-lock.json
  ui/package.json
Labels: area/ui

#881 api: Returns conflict when inserting an existing namespace
  api/nsadm/service.go
  api/nsadm/service_test.go
  api/routes/nsadm.go
Labels: area/api

#883 ui: Show message when namespace name already in use
  ui/src/components/app_bar/namespace/NamespaceAdd.vue
Labels: area/ui

#887 api: fix migrations to remove orphan sessions and records
  api/store/mongo/migrations.go
Labels: area/api

#894 ui: Adjustment on the app bar to improve viewing on mobile
  ui/src/assets/logo-inverted-only-cloud.png
  ui/src/components/app_bar/AppBar.vue
  ui/src/components/app_bar/namespace/NamespaceMenu.vue
  ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js
Labels: area/ui

#896 api: padronize error var declaration
  api/nsadm/service.go
Labels: area/api

#898 ui: fix showing the navigation drawer on mobile
  ui/src/App.vue
  ui/src/components/app_bar/AppBar.vue
  ui/tests/unit/components/app_bar/AppBar.spec.js
Labels: area/ui

#899 cli: fix the error when the provided input is not enough
  cli/main.go
Labels: area/cli, status/needs-review

#905 cli: display more meaningful errors to the user
  cli/error.go
  cli/service.go
Labels: area/cli

#876 Implemented caching mechanism for API store
  .env
  api/authsvc/service.go
  api/authsvc/service_test.go
  api/go.mod
  api/go.sum
  api/main.go
  api/store/cache/cache.go
  api/store/cache/cache_null.go
  api/store/cache/cache_redis.go
  api/store/mocks/cache.go
  api/store/mongo/device_store.go
  api/store/mongo/namespace_store.go
  api/store/mongo/store.go
  api/store/mongo/store_test.go
  bin/docker-compose
  cli/go.sum
  cli/main.go
  docker-compose.cache.yml
  docker-compose.yml
Labels: area/api
