Repository shellhub-io/shellhub, pull requests merged in 2021-07, with the labels that each got.

#1080 devscripts: add --fix option to pkg lint
  devscripts/lint-code
Labels: area/scripts, status/needs-review

#1078 ui: apply design pattern in UI tests
  ui/tests/unit/components/app_bar/max_device/MaxDevice.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceAdd.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceInstructions.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceNewMember.spec.js
  ui/tests/unit/components/app_bar/notification/Notification.spec.js
  ui/tests/unit/components/box/BoxMessage.spec.js
  ui/tests/unit/components/device/Device.spec.js
  ui/tests/unit/components/device/DeviceAdd.spec.js
  ui/tests/unit/components/device/DeviceDelete.spec.js
  ui/tests/unit/components/device/DeviceIcon.spec.js
  ui/tests/unit/components/device/DeviceList.spec.js
  ui/tests/unit/components/device/DevicePendingList.spec.js
  ui/tests/unit/components/device/DeviceRejectedList.spec.js
  ui/tests/unit/components/filter/Date.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRule.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
  ui/tests/unit/components/public_key/KeyFormDialog.spec.js
  ui/tests/unit/components/public_key/PublicKey.spec.js
  ui/tests/unit/components/public_key/PublicKeyList.spec.js
  ui/tests/unit/components/session/Session.spec.js
  ui/tests/unit/components/session/SessionDetails.spec.js
  ui/tests/unit/components/session/SessionList.spec.js
  ui/tests/unit/components/session/SessionPlay.spec.js
  ui/tests/unit/components/setting/SettingNamespace.spec.js
  ui/tests/unit/components/setting/SettingPrivateKeys.spec.js
  ui/tests/unit/components/setting/SettingProfile.spec.js
  ui/tests/unit/components/snackbar/SnackbarError.spec.js
  ui/tests/unit/components/snackbar/SnackbarSuccess.spec.js
  ui/tests/unit/components/welcome/Welcome.spec.js
  ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js
  ui/tests/unit/store/Auth.spec.js
  ui/tests/unit/store/Devices.spec.js
  ui/tests/unit/store/Firewalls.spec.js
  ui/tests/unit/store/Modals.spec.js
  ui/tests/unit/store/Namespaces.spec.js
  ui/tests/unit/store/Notification.spec.js
  ui/tests/unit/store/PrivateKeys.spec.js
  ui/tests/unit/store/PublicKeys.spec.js
  ui/tests/unit/store/Sessions.spec.js
  ui/tests/unit/store/Snackbar.spec.js
  ui/tests/unit/store/Stats.spec.js
  ui/tests/unit/views/Dashboard.spec.js
Labels: area/ui

#1081 ui: add tests
  ui/src/components/app_bar/namespace/NamespaceAdd.vue
  ui/src/components/app_bar/namespace/NamespaceDelete.vue
  ui/src/components/app_bar/namespace/NamespaceInstructions.vue
  ui/src/components/app_bar/namespace/NamespaceNewMember.vue
  ui/tests/unit/components/app_bar/namespaces/NamespaceAdd.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceDelete.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceInstructions.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceNewMember.spec.js
Labels: area/ui, status/work-in-progress

#1096 ui: add tests for app bar component
  ui/tests/unit/components/app_bar/AppBar.spec.js
Labels: area/ui

#1097 ui: add tests for device components
  ui/src/components/device/Device.vue
  ui/src/components/device/DeviceActionButton.vue
  ui/src/components/device/DeviceDelete.vue
  ui/src/components/device/DeviceDetails.vue
  ui/src/components/device/DeviceList.vue
  ui/src/components/device/DevicePendingList.vue
  ui/src/components/device/DeviceRejectedList.vue
  ui/src/components/device/DeviceRename.vue
  ui/tests/unit/components/device/Device.spec.js
  ui/tests/unit/components/device/DeviceActionButton.spec.js
  ui/tests/unit/components/device/DeviceAdd.spec.js
  ui/tests/unit/components/device/DeviceDelete.spec.js
  ui/tests/unit/components/device/DeviceDetails.spec.js
  ui/tests/unit/components/device/DeviceIcon.spec.js
  ui/tests/unit/components/device/DeviceList.spec.js
  ui/tests/unit/components/device/DevicePendingList.spec.js
  ui/tests/unit/components/device/DeviceRejectedList.spec.js
  ui/tests/unit/components/device/DeviceRename.spec.js
Labels: area/ui

#1098 api: add stats store interface
  api/store/mongo/stats_store.go
  api/store/mongo/store.go
  api/store/stats_store.go
  api/store/store.go
Labels: area/api, status/work-in-progress

#1105 cli: fix error message on add-user-namespace
  cli/error.go
  cli/service.go
Labels: area/cli, status/needs-review

#1110 ui: add snapshots for UI
  ui/tests/unit/__snapshots__/App.spec.js.snap
  ui/tests/unit/components/app_bar/__snapshots__/AppBar.spec.js.snap
  ui/tests/unit/components/app_bar/max_device/__snapshots__/MaxDevice.spec.js.snap
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceAdd.spec.js.snap
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceDelete.spec.js.snap
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceInstructions.spec.js.snap
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceMenu.spec.js.snap
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceNewMember.spec.js.snap
  ui/tests/unit/components/app_bar/notification/__snapshots__/Notification.spec.js.snap
  ui/tests/unit/components/box/__snapshots__/BoxMessage.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/Device.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceActionButton.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceAdd.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceDelete.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceIcon.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DevicePendingList.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceRejectedList.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceRename.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/KeyDelete.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/PublicKeyList.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/Session.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionClose.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionDeleteRecord.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingPrivateKeys.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingProfile.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingSecurity.spec.js.snap
  ui/tests/unit/components/snackbar/__snapshots__/Snackbar.spec.js.snap
  ui/tests/unit/components/snackbar/__snapshots__/SnackbarCopy.spec.js.snap
  ui/tests/unit/components/snackbar/__snapshots__/SnackbarError.spec.js.snap
  ui/tests/unit/components/snackbar/__snapshots__/SnackbarSuccess.spec.js.snap
  ui/tests/unit/components/terminal/__snapshots__/TerminalDialog.spec.js.snap
  ui/tests/unit/components/welcome/__snapshots__/Welcome.spec.js.snap
  ui/tests/unit/components/welcome/__snapshots__/WelcomeFirstScreen.spec.js.snap
  ui/tests/unit/components/welcome/__snapshots__/WelcomeFourthScreen.spec.js.snap
  ui/tests/unit/components/welcome/__snapshots__/WelcomeSecondScreen.spec.js.snap
  ui/tests/unit/components/welcome/__snapshots__/WelcomeThirdScreen.spec.js.snap
  ui/tests/unit/views/__snapshots__/Dashboard.spec.js.snap
  ui/tests/unit/views/__snapshots__/DetailsDevice.spec.js.snap
  ui/tests/unit/views/__snapshots__/DetailsSession.spec.js.snap
  ui/tests/unit/views/__snapshots__/Devices.spec.js.snap
  ui/tests/unit/views/__snapshots__/FirewallRules.spec.js.snap
  ui/tests/unit/views/__snapshots__/Login.spec.js.snap
  ui/tests/unit/views/__snapshots__/PublicKeys.spec.js.snap
  ui/tests/unit/views/__snapshots__/Sessions.spec.js.snap
  ui/tests/unit/views/__snapshots__/Settings.spec.js.snap
  ui/tests/unit/views/__snapshots__/SignUp.spec.js.snap
Labels: area/ui

#1134 api: update service to interface generic
  api/apicontext/apicontext.go
  api/routes/auth.go
  cli/go.sum
Labels: area/api

#1140 ui: refactor UI views tests
  ui/src/views/DetailsDevice.vue
  ui/src/views/DetailsSession.vue
  ui/src/views/Devices.vue
  ui/src/views/FirewallRules.vue
  ui/src/views/Login.vue
  ui/src/views/PublicKeys.vue
  ui/src/views/Sessions.vue
  ui/src/views/Settings.vue
  ui/src/views/SignUp.vue
  ui/tests/unit/views/Dashboard.spec.js
  ui/tests/unit/views/DetailsDevice.spec.js
  ui/tests/unit/views/DetailsSession.spec.js
  ui/tests/unit/views/Devices.spec.js
  ui/tests/unit/views/FirewallRules.spec.js
  ui/tests/unit/views/Login.spec.js
  ui/tests/unit/views/LoginIsCloud.spec.js
  ui/tests/unit/views/LoginIsnotCloud.spec.js
  ui/tests/unit/views/PublicKeys.spec.js
  ui/tests/unit/views/Sessions.spec.js
  ui/tests/unit/views/Settings.spec.js
  ui/tests/unit/views/SignUp.spec.js
  ui/tests/unit/views/__snapshots__/Dashboard.spec.js.snap
  ui/tests/unit/views/__snapshots__/DetailsDevice.spec.js.snap
  ui/tests/unit/views/__snapshots__/DetailsSession.spec.js.snap
  ui/tests/unit/views/__snapshots__/Devices.spec.js.snap
  ui/tests/unit/views/__snapshots__/FirewallRules.spec.js.snap
  ui/tests/unit/views/__snapshots__/Login.spec.js.snap
  ui/tests/unit/views/__snapshots__/LoginIsCloud.spec.js.snap
  ui/tests/unit/views/__snapshots__/LoginIsnotCloud.spec.js.snap
  ui/tests/unit/views/__snapshots__/PublicKeys.spec.js.snap
  ui/tests/unit/views/__snapshots__/Sessions.spec.js.snap
  ui/tests/unit/views/__snapshots__/Settings.spec.js.snap
Labels: area/ui

#1143 api: add cache to avoid store overload
  api/cache/cache.go
  api/cache/cache_null.go
  api/cache/cache_redis.go
  api/server.go
  api/services/auth.go
  api/services/auth_test.go
  api/services/device_test.go
  api/services/namespace_test.go
  api/services/service.go
  api/services/session_test.go
  api/services/sshkeys_test.go
  api/services/user_test.go
  api/store/mongo/store.go
  api/store/mongo/store_test.go
  cli/main.go
Labels: area/api, status/needs-review

#1139 ui: refactor UI firewall rules tests
  ui/src/components/firewall_rule/FirewallRule.vue
  ui/src/components/firewall_rule/FirewallRuleDelete.vue
  ui/src/components/firewall_rule/FirewallRuleFormDialog.vue
  ui/src/components/firewall_rule/FirewallRuleList.vue
  ui/tests/unit/components/firewall_rule/FirewallRule.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
Labels: area/ui

#1142 ui: refactor UI keys tests
  ui/src/components/public_key/KeyDelete.vue
  ui/src/components/public_key/KeyFormDialog.vue
  ui/src/components/public_key/PublicKey.vue
  ui/src/components/public_key/PublicKeyList.vue
  ui/tests/unit/components/public_key/KeyDelete.spec.js
  ui/tests/unit/components/public_key/KeyFormDialog.spec.js
  ui/tests/unit/components/public_key/PublicKey.spec.js
  ui/tests/unit/components/public_key/PublicKeyList.spec.js
  ui/tests/unit/components/public_key/__snapshots__/KeyDelete.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/PublicKeyList.spec.js.snap
Labels: area/ui

#1144 ui: refactor UI settings tests
  ui/src/components/setting/SettingNamespace.vue
  ui/src/components/setting/SettingPrivateKeys.vue
  ui/tests/unit/components/setting/SettingNamespace.spec.js
  ui/tests/unit/components/setting/SettingPrivateKeys.spec.js
  ui/tests/unit/components/setting/SettingProfile.spec.js
  ui/tests/unit/components/setting/SettingSecurity.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingPrivateKeys.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingSecurity.spec.js.snap
Labels: area/ui

#1146 ui: refactor UI welcome tests
  ui/tests/unit/components/welcome/Welcome.spec.js
  ui/tests/unit/components/welcome/WelcomeFirstScreen.spec.js
  ui/tests/unit/components/welcome/WelcomeFourthScreen.spec.js
  ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js
  ui/tests/unit/components/welcome/WelcomeThirdScreen.spec.js
  ui/tests/unit/components/welcome/__snapshots__/WelcomeThirdScreen.spec.js.snap
Labels: area/ui

#1138 ui: refactor UI session tests
  ui/src/components/session/Session.vue
  ui/src/components/session/SessionClose.vue
  ui/src/components/session/SessionDeleteRecord.vue
  ui/src/components/session/SessionDetails.vue
  ui/src/components/session/SessionPlay.vue
  ui/tests/unit/components/session/Session.spec.js
  ui/tests/unit/components/session/SessionClose.spec.js
  ui/tests/unit/components/session/SessionDeleteRecord.spec.js
  ui/tests/unit/components/session/SessionDetails.spec.js
  ui/tests/unit/components/session/SessionList.spec.js
  ui/tests/unit/components/session/SessionPlay.spec.js
  ui/tests/unit/components/session/__snapshots__/Session.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionClose.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionDeleteRecord.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
Labels: area/ui

#1149 ui: fix on when inserting name in namespace
  ui/src/components/app_bar/namespace/NamespaceAdd.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/src/errors.js
  ui/src/vee-validate.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceAdd.spec.js
  ui/tests/unit/components/setting/SettingNamespace.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
Labels: area/ui
