Repository shellhub-io/shellhub, pull requests merged in 2021-12, with the labels that each got.

#1475 ui: fix show the update account dialog
  ui/src/components/billing/BillingWarning.vue
  ui/src/store/modules/users.js
  ui/src/views/Dashboard.vue
  ui/tests/unit/components/billing/BillingWarning.spec.js
Labels: area/ui

#1484 api: update store device toplist to a more effective query
  api/services/mocks/services.go
  api/store/device_store.go
  api/store/mocks/store.go
  api/store/mongo/device_store.go
  api/store/mongo/device_store_test.go
Labels: do-not-merge, status/work-in-progress, area/api

#1485 ui: disable closing dialog when user clicks outside dialog
  ui/src/components/device/DeviceChooser.vue
Labels: area/ui

#1487 ui: add system permission on device chooser component
  ui/src/authorizer.js
  ui/src/components/device/DeviceChooser.vue
  ui/tests/unit/components/device/DeviceChooser.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceChooser.spec.js.snap
Labels: area/ui

#1488 api: add migration to set last_login property to created_at
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_38.go
  api/store/mongo/migrations/migration_38_test.go
Labels: do-not-merge, area/api, go, status/ready-for-testing

#1503 ssh: update message when user can't access device
  ssh/session.go
Labels: area/ssh

#1500 api: avoid returning unused fields
  pkg/models/namespace.go
Labels: do-not-merge, area/api

#1504 ui: remove 'beta' word
  ui/src/components/app_bar/AppBar.vue
  ui/src/views/ForgotPassword.vue
  ui/src/views/Login.vue
  ui/src/views/SignUp.vue
  ui/src/views/UpdatePassword.vue
  ui/src/views/ValidationAccount.vue
  ui/tests/unit/components/app_bar/__snapshots__/AppBar.spec.js.snap
  ui/tests/unit/views/__snapshots__/ForgotPassword.spec.js.snap
  ui/tests/unit/views/__snapshots__/LoginIsCloud.spec.js.snap
  ui/tests/unit/views/__snapshots__/LoginIsnotCloud.spec.js.snap
  ui/tests/unit/views/__snapshots__/SignUp.spec.js.snap
  ui/tests/unit/views/__snapshots__/UpdatePassword.spec.js.snap
  ui/tests/unit/views/__snapshots__/ValidationAccount.spec.js.snap
Labels: area/ui

#1506 agent: update env options to use a preferred device identity
  agent/agent.go
  agent/main.go
Labels: area/agent

#1521 ui: create payment list component
  ui/src/components/billing/BillingIcon.vue
  ui/src/components/billing/BillingPaymentList.vue
  ui/src/components/setting/SettingBilling.vue
  ui/tests/unit/components/billing/BillingPaymentList.spec.js
  ui/tests/unit/components/billing/__snapshots__/BillingIcon.spec.js.snap
  ui/tests/unit/components/billing/__snapshots__/BillingPaymentList.spec.js.snap
  ui/tests/unit/components/setting/SettingBilling.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingBilling.spec.js.snap
Labels: area/ui

#1537 ui: fix localstorage from type to role
  ui/src/store/modules/namespaces.js
Labels: area/ui, javascript

#1538 ui: fix rendering setting not owner
  ui/src/components/setting/SettingBilling.vue
  ui/tests/unit/components/setting/SettingBilling.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingBilling.spec.js.snap
Labels: area/ui

#1540 cli, bin: rename type's references to role
  bin/add-user-namespace
  cli/main.go
Labels: status/needs-review, area/cli

#1539 Change view of actions to use menu template
  ui/src/components/app_bar/namespace/NamespaceMemberDelete.vue
  ui/src/components/app_bar/namespace/NamespaceMemberFormDialog.vue
  ui/src/components/app_bar/namespace/NamespaceMemberList.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/src/store/modules/namespaces.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceMemberDelete.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceMemberFormDialog.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceMemberList.spec.js
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceMemberDelete.spec.js.snap
  ui/tests/unit/components/app_bar/namespaces/__snapshots__/NamespaceMemberFormDialog.spec.js.snap
  ui/tests/unit/components/setting/SettingNamespace.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
Labels: area/ui

#1542 api: add break instruction on find member lambda function
  api/services/namespace.go
Labels: area/api, go

#1541 api, pkg: remove delete namespace permission from administrator
  api/pkg/guard/guard_test.go
  pkg/authorizer/permissions.go
Labels: area/api, status/needs-review, go

#1543 ui: remove own owner actions in namespace list members
  ui/src/components/app_bar/namespace/NamespaceMemberList.vue
Labels: area/ui

#1551 ui: add pricing estimation to subscription dialog
  ui/src/components/billing/BillingDialogPaymentMethod.vue
  ui/tests/unit/components/billing/BillingDialogPaymentMethod.spec.js
Labels: area/ui

#1550 api, pkg: remove function to get all roles and remove unused action
  api/pkg/guard/guard.go
  api/pkg/guard/guard_test.go
  pkg/authorizer/actions.go
  pkg/authorizer/authorizer.go
  pkg/authorizer/authorizer_test.go
  pkg/authorizer/permissions.go
Labels: area/api, status/needs-review, go, kind/refactor

#1553 ui: change view of actions to use menu template in firewall list
  ui/src/components/box/BoxMessage.vue
  ui/src/components/firewall_rule/FirewallRule.vue
  ui/src/components/firewall_rule/FirewallRuleDelete.vue
  ui/src/components/firewall_rule/FirewallRuleFormDialog.vue
  ui/src/components/firewall_rule/FirewallRuleList.vue
  ui/tests/unit/components/box/BoxMessage.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRule.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
Labels: area/ui

#1555 ui: change view of actions to use menu template in key list
  ui/src/components/box/BoxMessage.vue
  ui/src/components/public_key/KeyDelete.vue
  ui/src/components/public_key/KeyFormDialog.vue
  ui/src/components/public_key/PublicKey.vue
  ui/src/components/public_key/PublicKeyList.vue
  ui/src/components/setting/SettingPrivateKeys.vue
  ui/tests/unit/components/public_key/KeyDelete.spec.js
  ui/tests/unit/components/public_key/KeyFormDialog.spec.js
  ui/tests/unit/components/public_key/PublicKey.spec.js
  ui/tests/unit/components/public_key/__snapshots__/KeyDelete.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingPrivateKeys.spec.js.snap
Labels: area/ui

#1562 Topic/device list actions
  ui/src/components/device/DeviceActionButton.vue
  ui/src/components/device/DevicePendingList.vue
  ui/src/components/device/DeviceRejectedList.vue
  ui/tests/unit/components/device/DeviceActionButton.spec.js
  ui/tests/unit/components/device/DevicePendingList.spec.js
  ui/tests/unit/components/device/DeviceRejectedList.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceActionButton.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DevicePendingList.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceRejectedList.spec.js.snap
Labels: area/ui

#1563 ui: fix warnings about ui tests
  ui/tests/unit/views/Dashboard.spec.js
Labels: area/ui

#1564 ui: fix actions in session details and remove dead code
  ui/src/components/session/SessionDeleteRecord.vue
  ui/src/components/session/SessionDetails.vue
Labels: area/ui

#1568 api: add migration to increase the TTL time
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_40.go
  api/store/mongo/migrations/migration_40_test.go
Labels: area/api, go, status/ready-for-testing
