Repository shellhub-io/shellhub, pull requests merged in 2021-03, with the labels that each got.

#750 api: Fix login
  api/authsvc/service.go
  api/store/mongo/store.go
  api/store/store.go
Labels: area/api

#752 ui: Fix to show only one add device button on the dashboard
  ui/src/components/device/DeviceAdd.vue
  ui/src/views/Dashboard.vue
Labels: area/ui

#754 ui: Resolve tests warnings
  ui/tests/unit/App.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceDelete.spec.js
  ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js
  ui/tests/unit/components/box/BoxMessage.spec.js
  ui/tests/unit/components/public_key/KeyFormDialog.spec.js
Labels: area/ui

#757 Topic/return accepted device
  api/store/mongo/store.go
Labels: area/api

#756 ui: Add number of devices user
  ui/src/components/app_bar/AppBar.vue
  ui/src/components/app_bar/max_device/MaxDevice.vue
  ui/tests/unit/components/app_bar/max_device/MaxDevice.spec.js
Labels: area/ui

#758 ui: Pattern store code
  ui/src/store/api/auth.js
  ui/src/store/modules/auth.js
  ui/src/store/modules/firewall_rules.js
  ui/src/store/modules/namespaces.js
  ui/src/store/modules/public_keys.js
Labels: area/ui

#761 agent: Add i386 support to the Docker images
  .github/workflows/build-agent.yml
  agent/Dockerfile.i386
Labels: area/agent, area/ci-cd

#764 ui: standardize centralization of private keys tab
  ui/src/components/setting/SettingPrivateKeys.vue
Labels: area/ui

#772 ui: Resolve warnings generated by eslint
  ui/src/components/app_bar/namespace/NamespaceMenu.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/src/views/Login.vue
Labels: area/ui

#763 ui: Add billing page
  ui/src/components/app_bar/max_device/MaxDevice.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/tests/unit/components/app_bar/max_device/MaxDevice.spec.js
  ui/tests/unit/components/setting/SettingNamespace.spec.js
Labels: area/ui

#774 ui: Remove title and spacing of private keys tab
  ui/src/components/setting/SettingPrivateKeys.vue
Labels: area/ui

#780 readme: update development environment setup
  README.md
Labels: area/docs

#784 api: Add function to update namespace
  api/store/mocks/store.go
  api/store/mongo/store.go
  api/store/mongo/store_test.go
  api/store/store.go
Labels: area/api

#781 ui: adapt height in namespace menu
  ui/src/components/app_bar/namespace/NamespaceMenu.vue
  ui/tests/unit/components/app_bar/namespaces/NamespaceMenu.spec.js
Labels: area/ui

#793 Avoid using `sh <(curl ...)` syntax as it does not work in Busybox
  gateway/kickstart.sh
  ui/src/components/device/DeviceAdd.vue
  ui/src/components/welcome/Welcome.vue
  ui/tests/unit/components/device/DeviceAdd.spec.js
  ui/tests/unit/components/welcome/Welcome.spec.js
  ui/tests/unit/components/welcome/WelcomeSecondScreen.spec.js
Labels: area/docker, kind/bug

#791 agent: Fixes utmp/wtmp recording on 64-bit systems
  agent/sshd/utmp.go
  agent/sshd/utmp_timeval_time32.go
  agent/sshd/utmp_timeval_time64.go
Labels: area/agent, kind/bug, status/needs-review

#794 ssh: fix key login when using terminal
  ssh/server.go
Labels: area/ssh, status/needs-review

#802 gateway: Fix /info to use X-Forwarded-Host to generate URLs
  gateway/shellhub.conf
Labels: area/docker

#804 ui: add private key validation check
  ui/src/components/public_key/KeyFormDialog.vue
  ui/src/store/modules/private_keys.js
  ui/src/vee-validate.js
Labels: area/ui

#805 api: Add name field to update user from admin
  api/store/mocks/store.go
  api/store/mongo/store.go
  api/store/mongo/store_test.go
  api/store/store.go
Labels: area/api

#806 api: fix error on pubkeys with different tenant
  api/sshkeys/service.go
  api/sshkeys/service_test.go
  api/store/mongo/migrations.go
Labels: area/api, status/work-in-progress

#810 api: update EditNamespace get owner by id instead of username
  api/nsadm/service.go
  api/nsadm/service_test.go
  api/routes/nsadm.go
Labels: area/api

#782 ssh: compare hostname with a regex
  api/main.go
  api/routes/sshkeys.go
  api/sshkeys/service.go
  api/store/mongo/store.go
  api/store/mongo/store_test.go
  pkg/api/client/client_internal.go
  pkg/models/publickey.go
  ssh/server.go
  ssh/ssh2ws.go
Labels: area/api, area/ssh

#788 ui: Add hostname field in the public key
  ui/src/components/public_key/KeyFormDialog.vue
  ui/src/components/public_key/PublicKeyList.vue
  ui/src/store/api/public_keys.js
Labels: area/ui

#824 ssh: fix permission denied message when connection fails
  ssh/server.go
Labels: area/ssh

#833 api: generate jwt token with user id data
  api/authsvc/service.go
  api/routes/auth.go
Labels: area/api

#832 Topic/modify snackbar message
  ui/src/views/Login.vue
Labels: area/ui
