Repository shellhub-io/shellhub, pull requests merged in 2021-11, with the labels that each got.

#1420 ui: fix redirection router's bug
  ui/src/views/Login.vue
Labels: area/ui

#1422 ui: remove code that is not needed
  ui/src/layouts/AppLayout.vue
  ui/tests/unit/layouts/__snapshots__/AppLayout.spec.js.snap
Labels: area/ui

#1423 ui: redirect to login route after activating account
  ui/src/views/ValidationAccount.vue
Labels: area/ui

#1424 ui: fix the user can select 3 devices or less
  ui/src/components/device/DeviceChooser.vue
Labels: area/ui

#1425 ui: add message when account is not active in enterprise version
  ui/src/views/Login.vue
  ui/tests/unit/views/LoginIsnotCloud.spec.js
  ui/tests/unit/views/__snapshots__/LoginIsCloud.spec.js.snap
  ui/tests/unit/views/__snapshots__/LoginIsnotCloud.spec.js.snap
Labels: area/ui

#1450 Add keep-alive system to websocket tunnel
  agent/go.mod
  agent/go.sum
  agent/main.go
  api/go.sum
  api/routes/device.go
  api/server.go
  api/services/device.go
  api/services/device_test.go
  api/services/mocks/services.go
  api/store/device_store.go
  api/store/mocks/store.go
  api/store/mongo/device_store.go
  api/store/mongo/device_store_test.go
  cli/go.sum
  go.mod
  openapi/spec/resources/devices/internal/heartbeat.yaml
  pkg/api/internalclient/client_internal.go
  pkg/api/internalclient/mocks/internalclient.go
  pkg/connman/connman.go
  pkg/httptunnel/httptunnel.go
  pkg/revdial/revdial.go
  ssh/go.mod
  ssh/go.sum
  ssh/main.go
Labels: area/agent, area/api, area/ssh

#1451 ui: check ownership in userwarning
  ui/src/components/billing/BillingWarning.vue
  ui/src/components/device/DeviceChooser.vue
  ui/tests/unit/components/billing/BillingWarning.spec.js
  ui/tests/unit/components/billing/__snapshots__/BillingWarning.spec.js.snap
  ui/tests/unit/components/device/DeviceChooser.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceChooser.spec.js.snap
Labels: area/ui

#1453 cli: organize code and use validator
  cli/error.go
  cli/go.mod
  cli/main.go
  cli/service.go
  cli/service_test.go
  cli/utils.go
Labels: go, kind/refactor, area/cli

#1471 ui: run npm audit fix
  ui/package-lock.json
Labels: area/ui
