Repository shellhub-io/shellhub, pull requests merged in 2021-02, with the labels that each got.

#699 pkg: fix tunnelDial func to dial host:port
  pkg/api/client/client_public.go
Labels: Area/Agent

#702 api: convert namespace to lower-case before inserting into db
  api/nsadm/service.go
  api/store/mongo/migrations.go
Labels: area/api, kind/bug

#705 ui: Fix showing terminal in device details when device is offline
  ui/src/components/device/DeviceDetails.vue
Labels: area/ui

#706 devscripts: add gen-mock script
  api/Dockerfile
  devscripts/README.md
  devscripts/gen-mock
Labels: area/scripts

#707 api: fix return parameter from ListUsers func
  api/store/mongo/store.go
Labels: area/api

#709 ui: Fix device name update
  ui/src/store/modules/devices.js
  ui/tests/unit/store/Devices.spec.js
Labels: area/ui, status/needs-review

#712 bin: Fix search for name to username in add-namespace script
  bin/add-namespace
Labels: area/scripts

#710 ui: Show namespace owner when user does not owner
  ui/src/components/setting/SettingNamespace.vue
  ui/tests/unit/components/setting/SettingNamespace.spec.js
Labels: area/ui, status/needs-review

#714 api: small fix on formatting
  .gitignore
  api/authsvc/service.go
  api/main.go
Labels: area/api

#715 makefile: exit when there is no mongo container
  Makefile
Labels: area/scripts

#728 agent: docker-compose.dev.yml started agent container with hard-coded SHELLHUB_SERVER_ADDRESS
  docker-compose.dev.yml
Labels: area/agent

#734 ui: Standardize firewall rule names according to the project
  ui/src/components/box/BoxMessage.vue
  ui/src/components/firewall_rule/FirewallRule.vue
  ui/src/components/firewall_rule/FirewallRuleDelete.vue
  ui/src/components/firewall_rule/FirewallRuleFormDialog.vue
  ui/src/components/firewall_rule/FirewallRuleList.vue
  ui/src/router/index.js
  ui/src/views/FirewallRules.vue
  ui/tests/unit/components/firewall_rule/FirewallRule.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
Labels: area/ui
