Repository shellhub-io/shellhub, pull requests merged in 2022-03, with the labels that each got.

#1768 api: fix down on migration 42
  api/store/mongo/migrations/migration_42.go
  api/store/mongo/migrations/migration_42_test.go
Labels: kind/bug, area/api, status/needs-review, go

#1769 api: change how public_key is merged when migration 42 is down
  api/store/mongo/migrations/migration_42.go
Labels: kind/bug, area/api, status/needs-review, go

#1779 ui: add small fixes
  ui/src/components/public_key/PublicKeyFormDialogEdit.vue
  ui/src/components/tag/TagSelector.vue
  ui/tests/unit/components/public_key/PublicKeyFormDialogEdit.spec.js
Labels: area/ui

#1780 ui: fix namespace auto switch
  ui/src/components/namespace/Namespace.vue
  ui/tests/unit/components/namespaces/Namespace.spec.js
Labels: area/ui

#1764 api, pkg, openapi: add tags to firewall rules
  api/services/mocks/services.go
  api/store/firewall_tags_store.go
  api/store/mocks/store.go
  api/store/mongo/firewall_tags_store.go
  api/store/mongo/firewall_tags_store_test.go
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_43.go
  api/store/mongo/migrations/migration_43_test.go
  api/store/mongo/store_test.go
  api/store/mongo/tags_store.go
  api/store/mongo/tags_store_test.go
  api/store/store.go
  openapi/cloud-openapi.yaml
  openapi/spec/resources/firewall/model/firewall_rules_hostname.yaml
  openapi/spec/resources/firewall/model/firewall_rules_tags.yaml
  openapi/spec/resources/firewall/rules.yaml
  openapi/spec/resources/firewall/rules_id.yaml
  openapi/spec/resources/firewall/rules_id_tags.yaml
  pkg/authorizer/actions.go
  pkg/authorizer/permissions.go
  pkg/models/firewall.go
Labels: kind/feature, area/api, status/needs-review, go, product/cloud, status/ready-for-testing, openapi

#1766 ui: Adds tag feature to the firewall rules dialog
  ui/src/components/firewall_rule/FirewallRule.vue
  ui/src/components/firewall_rule/FirewallRuleFormDialogAdd.vue
  ui/src/components/firewall_rule/FirewallRuleFormDialogEdit.vue
  ui/src/components/firewall_rule/FirewallRuleList.vue
  ui/src/store/api/firewall_rules.js
  ui/tests/unit/components/firewall_rule/FirewallRule.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogAdd.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogEdit.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
  ui/tests/unit/components/public_key/PublicKey.spec.js
Labels: area/ui

#1781 pkg: fix retrial client to detect network outages
  cli/go.sum
  pkg/api/client/client.go
  pkg/api/internalclient/client.go
Labels: area/agent, status/needs-review

#1805 ui: fix default value of tagChoices
  ui/src/components/firewall_rule/FirewallRuleFormDialogEdit.vue
  ui/src/vee-validate.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogEdit.spec.js
Labels: area/ui, status/work-in-progress

#1807 ui: fix empty name in page refresh
  ui/src/components/namespace/NamespaceRename.vue
  ui/tests/unit/components/namespaces/NamespaceRename.spec.js
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceRename.spec.js.snap
Labels: area/ui

#1829 api: fix duplicated fingerprint access
  api/routes/sshkeys.go
  api/store/mongo/publickey_store.go
  api/store/mongo/publickey_store_test.go
Labels: area/api, status/require-tests

#1831 ui: fix public key default value
  ui/src/components/public_key/PublicKeyFormDialogEdit.vue
  ui/tests/unit/components/public_key/PublicKeyFormDialogEdit.spec.js
Labels: area/ui
