Repository shellhub-io/shellhub, pull requests merged in 2022-02, with the labels that each got.

#1671 ui: block actions when the role is same
  ui/src/components/namespace/NamespaceMemberDelete.vue
  ui/src/components/namespace/NamespaceMemberFormDialog.vue
Labels: area/ui

#1670 ui: show menu in session details when there is recorded session
  ui/src/components/session/SessionDetails.vue
  ui/tests/unit/components/session/SessionDetails.spec.js
  ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap
Labels: area/ui

#1672 ui: modify time format display in session list
  ui/src/components/filter/date.js
  ui/src/components/session/SessionList.vue
  ui/tests/unit/components/filter/Date.spec.js
  ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap
Labels: area/ui

#1681 ui: fix console warnings
  ui/src/components/device/DeviceActionButton.vue
  ui/src/components/namespace/NamespaceDelete.vue
  ui/tests/unit/components/namespaces/NamespaceDelete.spec.js
Labels: area/ui

#1683 ui: refator member delete component
  ui/src/components/namespace/NamespaceMemberDelete.vue
  ui/src/components/namespace/NamespaceMemberList.vue
  ui/tests/unit/components/namespaces/NamespaceMemberDelete.spec.js
  ui/tests/unit/components/namespaces/NamespaceMemberList.spec.js
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberDelete.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberList.spec.js.snap
Labels: area/ui

#1684 ui: create component to add member in namespace
  ui/src/components/namespace/NamespaceMemberFormDialogAdd.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/tests/unit/components/namespaces/NamespaceMemberFormDialogAdd.spec.js
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberFormDialogAdd.spec.js.snap
  ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
Labels: area/ui

#1690 ui: change color of buttons on firewall and public when disabled
  ui/src/components/firewall_rule/FirewallRuleFormDialog.vue
  ui/src/components/public_key/KeyFormDialog.vue
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap
Labels: area/ui

#1687 ui: remove v-if in fragment
  ui/src/components/session/SessionDetails.vue
  ui/src/components/session/SessionList.vue
  ui/src/components/session/SessionPlay.vue
  ui/tests/unit/components/session/SessionDetails.spec.js
  ui/tests/unit/components/session/SessionList.spec.js
  ui/tests/unit/components/session/__snapshots__/SessionDetails.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionList.spec.js.snap
  ui/tests/unit/components/session/__snapshots__/SessionPlay.spec.js.snap
Labels: area/ui

#1689 ui: create component to add firewall rule in namespace
  ui/src/components/box/BoxMessage.vue
  ui/src/components/firewall_rule/FirewallRule.vue
  ui/src/components/firewall_rule/FirewallRuleFormDialogAdd.vue
  ui/tests/unit/components/firewall_rule/FirewallRule.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogAdd.spec.js
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRule.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialogAdd.spec.js.snap
Labels: area/ui

#1693 ui: create component to add public key
  ui/src/components/box/BoxMessage.vue
  ui/src/components/public_key/PublicKey.vue
  ui/src/components/public_key/PublicKeyFormDialogAdd.vue
  ui/tests/unit/components/public_key/PublicKey.spec.js
  ui/tests/unit/components/public_key/PublicKeyFormDialogAdd.spec.js
  ui/tests/unit/components/public_key/__snapshots__/PublicKey.spec.js.snap
  ui/tests/unit/components/public_key/__snapshots__/PublicKeyFormDialogAdd.spec.js.snap
Labels: area/ui

#1709 ui: fix variable name used to add the firewall
  ui/src/components/firewall_rule/FirewallRuleFormDialogAdd.vue
Labels: area/ui

#1710 ui: create unique component only for public key deletion
  ui/src/components/public_key/PublicKeyDelete.vue
  ui/src/components/public_key/PublicKeyList.vue
  ui/tests/unit/components/public_key/PublicKeyDelete.spec.js
  ui/tests/unit/components/public_key/PublicKeyList.spec.js
  ui/tests/unit/components/public_key/__snapshots__/PublicKeyDelete.spec.js.snap
Labels: area/ui

#1712 ui: refactor the component firewall rule delete
  ui/src/components/firewall_rule/FirewallRuleDelete.vue
  ui/src/components/firewall_rule/FirewallRuleList.vue
  ui/tests/unit/components/firewall_rule/FirewallRuleDelete.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleDelete.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleList.spec.js.snap
Labels: area/ui

#1713 ui: create unique component only for public key editing
  ui/src/components/firewall_rule/FirewallRuleFormDialogEdit.vue
  ui/src/components/firewall_rule/FirewallRuleList.vue
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialog.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleFormDialogEdit.spec.js
  ui/tests/unit/components/firewall_rule/FirewallRuleList.spec.js
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialog.spec.js.snap
  ui/tests/unit/components/firewall_rule/__snapshots__/FirewallRuleFormDialogEdit.spec.js.snap
Labels: area/ui

#1714 ui: refactor the component tag delete
  ui/src/components/tag/TagDelete.vue
  ui/src/components/tag/TagList.vue
  ui/tests/unit/components/tag/TagDelete.spec.js
  ui/tests/unit/components/tag/TagList.spec.js
  ui/tests/unit/components/tag/__snapshots__/TagDelete.spec.js.snap
  ui/tests/unit/components/tag/__snapshots__/TagList.spec.js.snap
Labels: area/ui

#1716 api: update validator to v10
  agent/go.sum
  api/go.mod
  api/go.sum
  api/services/auth.go
  cli/go.sum
  go.mod
  pkg/models/firewall.go
  pkg/models/publickey.go
  pkg/validator/validator.go
  ssh/go.mod
  ssh/go.sum
Labels: area/agent, area/api, area/ssh, area/cli, docker

#1718 ui: refactor the component tag update
  ui/src/components/device/DeviceDetails.vue
  ui/src/components/device/DeviceList.vue
  ui/src/components/tag/TagFormUpdate.vue
  ui/tests/unit/components/device/DeviceDetails.spec.js
  ui/tests/unit/components/device/DeviceList.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
  ui/tests/unit/components/tag/TagFormUpdate.spec.js
  ui/tests/unit/components/tag/__snapshots__/TagFormUpdate.spec.js.snap
Labels: area/ui

#1715 ui: create unique component only for tag editing
  ui/src/components/tag/TagFormDialog.vue
  ui/src/components/tag/TagFormDialogEdit.vue
  ui/src/components/tag/TagList.vue
  ui/tests/unit/components/tag/TagFormDialog.spec.js
  ui/tests/unit/components/tag/TagFormDialogEdit.spec.js
  ui/tests/unit/components/tag/TagList.spec.js
  ui/tests/unit/components/tag/__snapshots__/TagFormDialog.spec.js.snap
  ui/tests/unit/components/tag/__snapshots__/TagFormDialogEdit.spec.js.snap
Labels: area/ui

#1719 ui: refactor the component device delete
  ui/src/components/device/DeviceDelete.vue
  ui/src/components/device/DeviceList.vue
  ui/tests/unit/components/device/DeviceDelete.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceDelete.spec.js.snap
Labels: area/ui

#1720 ui: refactor the component device rename
  ui/src/components/device/DeviceDetails.vue
  ui/src/components/device/DeviceRename.vue
  ui/tests/unit/components/device/DeviceDetails.spec.js
  ui/tests/unit/components/device/DeviceRename.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
  ui/tests/unit/components/device/__snapshots__/DeviceRename.spec.js.snap
Labels: area/ui

#1734 ui: remove unused files after refactoring components
  ui/src/components/public_key/KeyFormDialog.vue
  ui/tests/unit/components/public_key/KeyFormDialog.spec.js
  ui/tests/unit/components/public_key/__snapshots__/KeyFormDialog.spec.js.snap
Labels: area/ui

#1735 ui: fix device delete permission in device details
  ui/src/components/device/DeviceDetails.vue
  ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
Labels: area/ui

#1736 ui: fix device rename permission in device details
  ui/src/components/device/DeviceDetails.vue
  ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
Labels: area/ui

#1673 api: add documentation, change variables' name and checks.
  api/services/namespace.go
Labels: area/api, status/needs-review, go

#1737 api: fix public key loop with wrong range definition
  api/store/mongo/device_store_tags.go
  api/store/mongo/device_store_tags_test.go
Labels: kind/bug, area/api, status/require-tests

#1722 ui: update public key form to choose filtering
  ui/src/components/public_key/PublicKey.vue
  ui/src/components/public_key/PublicKeyDelete.vue
  ui/src/components/public_key/PublicKeyFormDialogAdd.vue
  ui/src/components/public_key/PublicKeyFormDialogEdit.vue
  ui/src/components/public_key/PublicKeyList.vue
  ui/src/store/api/public_keys.js
  ui/tests/unit/components/public_key/PublicKey.spec.js
  ui/tests/unit/components/public_key/PublicKeyFormDialogAdd.spec.js
  ui/tests/unit/components/public_key/PublicKeyFormDialogEdit.spec.js
  ui/tests/unit/components/public_key/PublicKeyList.spec.js
  ui/tests/unit/components/public_key/__snapshots__/PublicKeyFormDialogEdit.spec.js.snap
Labels: area/ui, status/work-in-progress

#1738 api: fix inverse filter evaluation and add tests to it
  api/services/sshkeys.go
  api/services/sshkeys_test.go
Labels: kind/bug, area/api, status/needs-review, go
