Repository shellhub-io/shellhub, pull requests merged in 2022-01, with the labels that each got.

#1590 ui: fix app layout after JWT expires
  ui/src/store/helpers/http.js
Labels: area/ui

#1589 api: add worker to delete session records
  .env
  api/worker.go
  docker-compose.yml
Labels: kind/feature, status/work-in-progress, area/api, status/needs-review, go, status/require-tests

#1613 ui: device list page improvements
  ui/src/components/device/DeviceList.vue
  ui/tests/unit/components/device/DeviceList.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
Labels: area/ui

#1615 ui: add payment layout form in vuetify configs
  ui/src/components/billing/BillingDialogPaymentMethod.vue
  ui/src/plugins/vuetify.js
Labels: area/ui

#1619 ui: apply dark mode to pages set to light mode only
  ui/src/views/ForgotPassword.vue
  ui/src/views/SignUp.vue
  ui/src/views/UpdatePassword.vue
  ui/src/views/ValidationAccount.vue
  ui/tests/unit/views/__snapshots__/ForgotPassword.spec.js.snap
  ui/tests/unit/views/__snapshots__/SignUp.spec.js.snap
  ui/tests/unit/views/__snapshots__/UpdatePassword.spec.js.snap
  ui/tests/unit/views/__snapshots__/ValidationAccount.spec.js.snap
Labels: area/ui

#1618 ui: restore gitter in appBar
  ui/src/components/app_bar/AppBar.vue
  ui/tests/unit/components/app_bar/__snapshots__/AppBar.spec.js.snap
Labels: area/ui

#1621 ui: change grid system in login screen
  ui/src/views/Login.vue
  ui/tests/unit/views/__snapshots__/LoginIsCloud.spec.js.snap
  ui/tests/unit/views/__snapshots__/LoginIsnotCloud.spec.js.snap
Labels: area/ui

#1623 ui: run npm audit fix command
  ui/package-lock.json
Labels: area/ui

#1624 ui: move to namespace components to root of component directories
  ui/src/components/namespace/Namespace.vue
  ui/src/components/namespace/NamespaceAdd.vue
  ui/src/components/namespace/NamespaceDelete.vue
  ui/src/components/namespace/NamespaceInstructions.vue
  ui/src/components/namespace/NamespaceMemberDelete.vue
  ui/src/components/namespace/NamespaceMemberFormDialog.vue
  ui/src/components/namespace/NamespaceMemberList.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/src/components/user/UserWarning.vue
  ui/src/layouts/AppLayout.vue
  ui/tests/unit/components/namespaces/Namespace.spec.js
  ui/tests/unit/components/namespaces/NamespaceAdd.spec.js
  ui/tests/unit/components/namespaces/NamespaceDelete.spec.js
  ui/tests/unit/components/namespaces/NamespaceInstructions.spec.js
  ui/tests/unit/components/namespaces/NamespaceMemberDelete.spec.js
  ui/tests/unit/components/namespaces/NamespaceMemberFormDialog.spec.js
  ui/tests/unit/components/namespaces/NamespaceMemberList.spec.js
  ui/tests/unit/components/namespaces/__snapshots__/Namespace.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceAdd.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceDelete.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceInstructions.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberDelete.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberFormDialog.spec.js.snap
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceMemberList.spec.js.snap
Labels: area/ui

#1625 ui: improvements in the view of tags in the device list
  ui/src/components/device/DeviceList.vue
  ui/tests/unit/components/device/DeviceList.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
Labels: area/ui

#1626 ui: restore navigation drawer to show on mobile
  ui/src/components/app_bar/AppBar.vue
  ui/src/layouts/AppLayout.vue
  ui/src/store/modules/layout.js
  ui/tests/unit/layouts/AppLayout.spec.js
  ui/tests/unit/layouts/__snapshots__/AppLayout.spec.js.snap
  ui/tests/unit/store/Layouts.spec.js
Labels: area/ui

#1628 ui: move rename namespace to component
  ui/src/components/namespace/NamespaceRename.vue
  ui/src/components/setting/SettingNamespace.vue
  ui/tests/unit/components/namespaces/NamespaceRename.spec.js
  ui/tests/unit/components/namespaces/__snapshots__/NamespaceRename.spec.js.snap
  ui/tests/unit/components/setting/SettingNamespace.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingNamespace.spec.js.snap
Labels: area/ui

#1575 api: split apicontext to an own package and add const to improve route's code redability
  api/pkg/apicontext/apicontext.go
  api/routes/auth.go
  api/routes/device.go
  api/routes/device_test.go
  api/routes/middleware/authorize.go
  api/routes/nsadm.go
  api/routes/session.go
  api/routes/sshkeys.go
  api/routes/stats.go
  api/routes/user.go
  api/server.go
  api/store/mongo/device_store.go
  api/store/mongo/firewall_store.go
  api/store/mongo/namespace_store.go
  api/store/mongo/publickey_store.go
  api/store/mongo/session_store.go
  api/store/mongo/stats_store.go
  api/store/mongo/user_store.go
Labels: area/api, status/needs-review, go, kind/refactor

#1635 ui: add connect device button in device list
  ui/src/components/device/DeviceList.vue
  ui/src/components/terminal/TerminalDialog.vue
  ui/tests/unit/components/device/__snapshots__/DeviceList.spec.js.snap
  ui/tests/unit/components/terminal/TerminalDialog.spec.js
  ui/tests/unit/components/terminal/__snapshots__/TerminalDialog.spec.js.snap
Labels: area/ui

#1627 ui: update settings view
  ui/src/components/billing/BillingIcon.vue
  ui/src/components/billing/BillingInvoiceList.vue
  ui/src/components/billing/BillingPaymentList.vue
  ui/src/components/setting/SettingBilling.vue
  ui/src/helpers/billInfoExtract.js
  ui/src/helpers/timestamp.js
  ui/src/store/api/namespaces.js
  ui/src/store/modules/billing.js
  ui/src/store/modules/namespaces.js
  ui/tests/unit/components/billing/BillingInvoiceList.spec.js
  ui/tests/unit/components/billing/BillingPaymentList.spec.js
  ui/tests/unit/components/billing/__snapshots__/BillingIcon.spec.js.snap
  ui/tests/unit/components/billing/__snapshots__/BillingInvoiceList.spec.js.snap
  ui/tests/unit/components/billing/__snapshots__/BillingPaymentList.spec.js.snap
  ui/tests/unit/components/setting/SettingBilling.spec.js
  ui/tests/unit/components/setting/__snapshots__/SettingBilling.spec.js.snap
  ui/tests/unit/store/Billing.spec.js
Labels: area/ui

#1636 pkg: set request retrials for http client
  pkg/api/client/client.go
  pkg/api/internalclient/client.go
Labels: status/work-in-progress, area/api

#1639 api: add limit to 3 tags on device
  api/services/device_tags.go
  api/services/device_tags_test.go
Labels: area/api, status/needs-review, go, kind/refactor

#1642 ui: refactor tag listing button
  ui/src/components/setting/tag/TagSelector.vue
  ui/tests/unit/components/setting/tag/TagSelector.spec.js
  ui/tests/unit/components/setting/tag/__snapshots__/TagSelector.spec.js.snap
Labels: area/ui

#1638 api: add package to working with MongoDB query filter
  api/routes/device.go
  api/store/mongo/device_store.go
  api/store/mongo/firewall_store.go
  api/store/mongo/namespace_store.go
  api/store/mongo/publickey_store.go
  api/store/mongo/queries/queries.go
  api/store/mongo/queries/queries_test.go
  api/store/mongo/session_store.go
  api/store/mongo/user_store.go
  api/store/mongo/utils.go
Labels: do-not-merge, area/api, status/needs-review, go, kind/refactor

#1648 Topic/tags refactor
  ui/src/components/setting/tag/TagFormUpdate.vue
Labels: area/ui

#1650 api: fix tag update to accept only unique tags
  api/services/device_tags.go
  api/services/device_tags_test.go
Labels: kind/bug, kind/feature, area/api, status/needs-review, go

#1647 api: add store method to list active instances
  api/store/billing_store.go
  api/store/mocks/store.go
  api/store/mongo/billing_store.go
  api/store/mongo/billing_store_test.go
  pkg/models/billing.go
Labels: area/api

#1651 ui: put the tag name in the plural
  ui/src/components/setting/tag/TagFormUpdate.vue
  ui/tests/unit/components/setting/tag/TagFormUpdate.spec.js
  ui/tests/unit/components/setting/tag/__snapshots__/TagFormUpdate.spec.js.snap
Labels: area/ui

#1655 ui: remove dark styles that are not needed
  ui/src/components/session/SessionPlay.vue
  ui/src/components/terminal/TerminalDialog.vue
Labels: area/ui

#1652 ui: add connect button in device details
  ui/src/components/device/DeviceDetails.vue
  ui/tests/unit/components/device/DeviceDetails.spec.js
  ui/tests/unit/components/device/__snapshots__/DeviceDetails.spec.js.snap
Labels: area/ui

#1654 ui: remove filter not using in billing list
  ui/src/components/billing/BillingInvoiceList.vue
Labels: area/ui

#1659 ui: move close icon to end of bar
  ui/src/components/terminal/TerminalDialog.vue
Labels: area/ui

#1658 ui: move tags components to root of component directories
  ui/src/components/device/Device.vue
  ui/src/components/device/DeviceDetails.vue
  ui/src/components/device/DeviceList.vue
  ui/src/components/setting/SettingTags.vue
  ui/src/components/tag/TagDelete.vue
  ui/src/components/tag/TagFormDialog.vue
  ui/src/components/tag/TagFormUpdate.vue
  ui/src/components/tag/TagList.vue
  ui/src/components/tag/TagSelector.vue
  ui/tests/unit/components/tag/TagDelete.spec.js
  ui/tests/unit/components/tag/TagFormDialog.spec.js
  ui/tests/unit/components/tag/TagFormUpdate.spec.js
  ui/tests/unit/components/tag/TagList.spec.js
  ui/tests/unit/components/tag/TagSelector.spec.js
  ui/tests/unit/components/tag/__snapshots__/TagDelete.spec.js.snap
  ui/tests/unit/components/tag/__snapshots__/TagFormDialog.spec.js.snap
  ui/tests/unit/components/tag/__snapshots__/TagFormUpdate.spec.js.snap
  ui/tests/unit/components/tag/__snapshots__/TagList.spec.js.snap
  ui/tests/unit/components/tag/__snapshots__/TagSelector.spec.js.snap
Labels: area/ui

#1641 api, cli, pkg: improve validator package with reflection.
  api/services/device_tags.go
  api/services/user.go
  api/services/utils.go
  cli/service.go
  pkg/validator/error.go
  pkg/validator/validate.go
  pkg/validator/validator.go
Labels: area/api, status/needs-review, go, kind/refactor, area/cli

#1664 api: update last_seen time from 60 to 120 seconds
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_41.go
  api/store/mongo/migrations/migration_41_test.go
Labels: kind/bug, area/api, status/needs-review, go
