Repository shellhub-io/shellhub, pull requests merged in 2023-08, with the labels that each got.

#3002 fix(ui): rewrote billing related texts
  ui/src/components/Billing/BillingWarning.vue
  ui/src/components/Devices/DeviceActionButton.vue
  ui/src/components/Namespace/NamespaceDelete.vue
  ui/src/components/Setting/SettingBilling.vue
  ui/tests/components/Billing/__snapshots__/BillingWarning.spec.ts.snap
Labels: area/ui, status/ready-for-testing

#3000 fix(ui): ConfirmAccount tests created
  ui/src/interfaces/INotifications.ts
  ui/src/views/ConfirmAccount.vue
  ui/tests/views/ConfirmAccount.spec.ts
  ui/tests/views/__snapshots__/ConfirmAccount.spec.ts.snap
Labels: area/ui, kind/refactor, status/ready-for-testing

#2986 refactor(api,pkg): improve UpdateDeviceStatus service's method
  api/routes/device.go
  api/services/device.go
  api/services/device_test.go
  api/services/errors.go
  api/services/mocks/services.go
  pkg/envs/envs.go
  pkg/models/namespace.go
Labels: area/api, go, product/cloud, product/enterprise

#3053 test(routes): implementing test cases of tag validation
  api/routes/device_test.go
  api/routes/healthcheck_test.go
  api/routes/nsadm_test.go
  api/routes/session_test.go
  api/routes/sshkeys_test.go
  api/routes/stats_test.go
  api/routes/tags_test.go
  api/routes/user_test.go
Labels: status/work-in-progress

#3021 fix: billing suggestions data table
  ui/src/components/Devices/DeviceChooser.vue
  ui/src/components/Devices/DeviceList.vue
  ui/src/components/Devices/DeviceListChooser.vue
  ui/src/store/modules/devices.ts
  ui/src/views/Devices.vue
  ui/tests/components/Devices/DeviceChooser.spec.ts
  ui/tests/components/Devices/DeviceListChooser.spec.ts
  ui/tests/components/Devices/__snapshots__/DeviceChooser.spec.ts.snap
  ui/tests/components/Devices/__snapshots__/DeviceListChooser.spec.ts.snap
Labels: kind/bug, area/ui, status/work-in-progress, kind/refactor

#3065 refactor(ui): billing device suggestion tab
  ui/src/components/Devices/DeviceChooser.vue
  ui/src/components/Devices/DeviceListChooser.vue
  ui/tests/components/Devices/DeviceChooser.spec.ts
  ui/tests/components/Devices/__snapshots__/DeviceListChooser.spec.ts.snap
Labels: area/ui, product/cloud, kind/refactor, status/ready-for-testing

#3069 fix(ui): sortable headers device list
  ui/src/components/Devices/DeviceList.vue
Labels: kind/bug, area/ui, product/cloud, product/enterprise
