Repository shellhub-io/shellhub, pull requests merged in 2023-05, with the labels that each got.

#2706 gateway,docker: add certbot to enable SSL certification on gateway
  bin/docker-compose
  docker-compose.autossl.yml
  docker-compose.httptohttps.yml
  docker-compose.yml
  gateway/Dockerfile
  gateway/conf.d/shellhub.conf
  gateway/entrypoint.sh
Labels: kind/feature, kind/refactor, Epic, docker

#2721 api,devscript: use go generation to build the mock interfaces
  api/services/service.go
  api/store/store.go
  devscripts/gen-mock
Labels: status/needs-review, go, kind/refactor

#2757 fix: ui new connection button pre-load rerouting to login page
  ui/src/layouts/AppLayout.vue
Labels: kind/bug, area/ui, status/needs-review, javascript

#2758 fix(api): avoid internal error when generic error occour
  api/pkg/echo/handlers/errors.go
Labels: worksforme, status/needs-review

#2782 fix(ssh): force exit when exec command is run on agent less than 0.9.3
  ssh/go.mod
  ssh/go.sum
  ssh/server/handler/ssh.go
Labels: status/needs-review, status/ready-for-testing

#2787 fix(ssh): fix force exit when exec on agent older than 0.9.3 to use right uid
  ssh/server/handler/ssh.go
Labels: area/ssh, status/needs-review, status/require-tests
