Repository shellhub-io/shellhub, pull requests merged in 2023-12, with the labels that each got.

#3340 fix(ui): device list not maintaining search filters on pagination
  ui/src/components/Devices/DeviceList.vue
  ui/tests/components/Devices/DeviceList.spec.ts
  ui/tests/components/Devices/__snapshots__/DeviceList.spec.ts.snap
Labels: area/ui, status/needs-review, javascript, status/ready-for-testing

#3342 chore(api): remove verbose logs
  api/workers/heartbeat.go
  api/workers/session_cleanup.go
Labels: area/api

#3361 fix(api): avoid error when nothing is updated on user data request
  api/routes/user.go
  api/routes/user_test.go
  api/services/mocks/services.go
  api/services/user.go
  api/services/user_test.go
  api/store/mongo/user_store.go
Labels: status/good-to-merge
