Repository shellhub-io/shellhub, pull requests merged in 2023-11, with the labels that each got.

#3237 refactor(api): optimize device listing query
  api/store/mongo/device_store.go
Labels: area/api

#3175 refactor(agent): remove duplication on osauth
  pkg/agent/pkg/osauth/auth.go
  pkg/agent/server/modes/host/authenticator.go
Labels: area/agent, status/ready-for-testing

#3268 fix(ui): fixed linting for UI vite and typescript configuration
  ui/tsconfig.json
  ui/vite.config.ts
Labels: area/ui, status/ready-for-testing

#3272 fix(ui): return defineModel to vite configuration
  ui/vite.config.ts
Labels: area/ui, status/needs-review

#3273 fix(ui): decode encodedURL non-ed signature
  ui/src/components/Terminal/TerminalDialog.vue
Labels: kind/bug, area/ui, javascript, status/ready-for-testing

#3274 chore(ui): added note for experimental defineModel
  ui/vite.config.ts
Labels: area/ui

#3258 refactor(ui): refactored profile settings to vue 3 composition api
  ui/src/components/Setting/SettingProfile.vue
  ui/tests/components/Setting/SettingProfile.spec.ts
  ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing

#3304 add index for tenant_id on recorded_sessions
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_62.go
  api/store/mongo/migrations/migration_62_test.go
Labels: area/api

#3303 fix(api): avoid device with duplicated name when accepting
  api/services/device.go
  api/services/device_test.go
  api/store/device_store.go
  api/store/mocks/store.go
  api/store/mongo/device_store.go
  api/store/mongo/device_store_test.go
Labels: status/needs-review

#3307 fix(ssh): avoid race conditions when saving the session
  pkg/agent/agent.go
  pkg/agent/server/server.go
Labels: area/agent

#3309 feat(ui): add validation modal for conflicted device names
  ui/src/components/AppBar/Notifications/Notification.vue
  ui/src/components/Devices/DeviceAcceptWarning.vue
  ui/src/components/Devices/DeviceActionButton.vue
  ui/src/components/Devices/DevicePendingList.vue
  ui/src/components/Devices/DeviceRejectedList.vue
  ui/src/components/Devices/DeviceRename.vue
  ui/src/components/User/UserWarning.vue
  ui/src/store/modules/devices.ts
  ui/src/store/modules/users.ts
  ui/tests/components/Devices/__snapshots__/DeviceAcceptWarning.spec.ts
  ui/tests/components/Devices/__snapshots__/__snapshots__/DeviceAcceptWarning.spec.ts.snap
Labels: kind/feature, area/ui, status/ready-for-testing
