Repository shellhub-io/shellhub, pull requests merged in 2023-07, with the labels that each got.

#2938 api(services): correct token
  api/services/auth.go
Labels: status/needs-review

#2927 passing context to services, creating constants and native error
  cli/main.go
  cli/services/namespaces.go
  cli/services/namespaces_test.go
  cli/services/services.go
  cli/services/users.go
  cli/services/users_test.go
Labels: area/cli

#2937 Improvement/replace router package
  agent/go.mod
  agent/go.sum
  agent/main.go
  agent/pkg/tunnel/tunnel.go
  go.mod
  pkg/httptunnel/httptunnel.go
  ssh/go.mod
  ssh/go.sum
  ssh/main.go
  ssh/pkg/tunnel/tunnel.go
Labels: status/needs-review

#2964 chore(api,docker): update golangci-lint version to 1.52.2
  api/Dockerfile
Labels: area/docker, docker

#2968 fix(ui): update deprecated sentry on main.ts
  ui/src/main.ts
Labels: area/ui, status/needs-review

#2971 fix(ui): changed alert text on billing for more context
  ui/src/components/Setting/SettingBilling.vue
Labels: area/ui, product/cloud

#2970 fix(api): change wrong name on field state to status on migration 57
  api/store/mongo/migrations/migration_57.go
Labels: area/api

#2974 fix(ui): added global reloading for caching browsers
  ui/src/main.ts
Labels: area/ui, javascript, status/ready-for-testing

#2912 Fix/signup test
  ui/src/views/Login.vue
  ui/src/views/SignUp.vue
  ui/tests/views/Login.spec.ts
  ui/tests/views/SignUp.spec.ts
  ui/tests/views/__snapshots__/SignUp.spec.ts.snap
Labels: area/ui, status/needs-review, javascript, kind/refactor

#2984 fix(ssh): enable connection with uppercase MAC address
  ssh/pkg/target/target.go
Labels: kind/bug, help-wanted, area/ssh, go, status/require-tests

#2991 fix(ui): excluded back forward listener to SettingBilling only
  ui/src/main.ts
Labels: area/ui

#2987 test(ui): update password test
  ui/src/views/UpdatePassword.vue
  ui/tests/views/Login.spec.ts
  ui/tests/views/UpdatePassword.spec.ts
  ui/tests/views/__snapshots__/UpdatePassword.spec.ts.snap
Labels: area/ui, status/work-in-progress, javascript, product/cloud, kind/refactor

#2988 refactor(agent): convert "agent" binary into a package
  agent/README.md
  agent/agent.go
  agent/go.mod
  agent/go.sum
  agent/init_docker.go
  agent/logo.png
  agent/main.go
  go.mod
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/pkg/keygen/keygen.go
  pkg/agent/pkg/osauth/auth.go
  pkg/agent/pkg/osauth/auth_test.go
  pkg/agent/pkg/osauth/user.go
  pkg/agent/pkg/selfupdater/updater.go
  pkg/agent/pkg/selfupdater/updater_docker.go
  pkg/agent/pkg/selfupdater/updater_native.go
  pkg/agent/pkg/sysinfo/network.go
  pkg/agent/pkg/sysinfo/osrelease.go
  pkg/agent/pkg/tunnel/tunnel.go
  pkg/agent/pkg/yescrypt/yescript.go
  pkg/agent/server/command/command_docker.go
  pkg/agent/server/command/command_native.go
  pkg/agent/server/pty.go
  pkg/agent/server/server.go
  pkg/agent/server/utmp/utmp.go
  pkg/agent/server/utmp/utmp_timeval_time32.go
  pkg/agent/server/utmp/utmp_timeval_time64.go
  pkg/agent/sftp.go
Labels: area/agent, go, kind/refactor, status/require-tests, Epic
