Repository shellhub-io/shellhub, pull requests merged in 2024-09, with the labels that each got.

#4134 chore(env): set connector env to be true by default
  .env
Labels: product/cloud, product/enterprise, status/good-to-merge

#4133 fix(ui): remove null setFilter store method from quickconnection
  ui/src/components/QuickConnection/QuickConnection.vue
Labels: kind/bug, area/ui, status/good-to-merge

#4161 fix(ui): typo on INamespaceInvite interface
  ui/src/interfaces/INamespace.ts
Labels: kind/bug, area/ui, status/good-to-merge

#4180 fix(agent,api,gateway,ssh): use air to watch pkg directory
  agent/.air.toml
  api/.air.toml
  gateway/.air.toml
  ssh/.air.toml
Labels: status/good-to-merge

#4184 fix(ui): retrieve tags when selecting the filter tags option for public keys
  ui/src/components/PublicKeys/PublicKeyAdd.vue
  ui/src/components/PublicKeys/PublicKeyEdit.vue
Labels: kind/bug, area/ui, status/ready-for-testing, status/good-to-merge

#4185 fix(ui): retrieve tags when selecting the filter tags option for firewall
  ui/src/components/firewall/FirewallRuleAdd.vue
  ui/src/components/firewall/FirewallRuleEdit.vue
Labels: kind/bug, area/ui, status/ready-for-testing, status/good-to-merge
