Repository shellhub-io/shellhub, pull requests merged in 2024-12, with the labels that each got.

#4377 fix(ui): remove unused binding in MemberEdit component
  ui/src/components/Team/Member/MemberEdit.vue
  ui/tests/components/Team/Member/__snapshots__/MemberEdit.spec.ts.snap
Labels: kind/bug, status/good-to-merge

#4382 feat(ui): add Tunnel List to device details interface
  docker-compose.yml
  ui/src/api/client/api.ts
  ui/src/api/http.ts
  ui/src/authorizer.ts
  ui/src/components/Tunnels/TunnelCreate.vue
  ui/src/components/Tunnels/TunnelDelete.vue
  ui/src/components/Tunnels/TunnelList.vue
  ui/src/envVariables.ts
  ui/src/interfaces/INotifications.ts
  ui/src/interfaces/ITunnel.ts
  ui/src/store/api/tunnels.ts
  ui/src/store/index.ts
  ui/src/store/modules/tunnels.ts
  ui/src/views/DetailsDevice.vue
  ui/tests/components/Tunnels/TunnelCreate.spec.ts
  ui/tests/components/Tunnels/TunnelDelete.spec.ts
  ui/tests/components/Tunnels/TunnelList.spec.ts
  ui/tests/components/Tunnels/__snapshots__/TunnelCreate.spec.ts.snap
  ui/tests/components/Tunnels/__snapshots__/TunnelDelete.spec.ts.snap
  ui/tests/components/Tunnels/__snapshots__/TunnelList.spec.ts.snap
  ui/tests/views/DetailsDevice.spec.ts
  ui/tests/views/__snapshots__/DetailsDevice.spec.ts.snap
Labels: kind/feature, area/ui, javascript, docker, product/enterprise, openapi, status/good-to-merge

#4385 fix(ui): adjust settings inputs to use flat variant when not editing
  ui/src/components/Namespace/NamespaceEdit.vue
  ui/src/components/Setting/SettingNamespace.vue
  ui/src/components/Setting/SettingProfile.vue
  ui/src/components/User/UserDelete.vue
  ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap
  ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4410 feat(ui): settings on main navigation drawer
  ui/src/components/Setting/SettingDrawer.vue
  ui/src/layouts/AppLayout.vue
  ui/src/views/Settings.vue
  ui/tests/components/Setting/SettingDrawer.spec.ts
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
  ui/tests/views/Settings.spec.ts
  ui/tests/views/__snapshots__/Settings.spec.ts.snap
Labels: kind/feature, area/ui, javascript, status/good-to-merge

#4412 fix(ui): enhance user input validation and error handling
  ui/src/views/Setup.vue
  ui/src/views/SignUp.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4419 fix(ui): enhance menu behavior and item visibility
  ui/src/layouts/AppLayout.vue
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4418 fix(ui): conditional rendering for billing components
  ui/src/components/Setting/SettingBilling.vue
  ui/tests/components/Setting/__snapshots__/SettingBilling.spec.ts.snap
Labels: kind/bug, area/ui, status/good-to-merge

#4428 fix(ui): enhance notification and authorization logic in UI components
  ui/src/authorizer.ts
  ui/src/components/AppBar/Notifications/Notification.vue
  ui/src/components/Team/ApiKeys/ApiKeyGenerate.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4429 fix(ui): enhance member invite error handling and conditional UI rendering
  ui/src/components/Team/Member/MemberInvite.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4411 fix(ssh): avoid pipe close before copy done on exec
  ssh/server/channels/session.go
  ssh/server/channels/utils.go
Labels: status/good-to-merge

#4430 Fix/remove block some routes
  api/routes/routes.go
Labels: area/api, status/good-to-merge

#4443 fix(ui): re-add `style` prop to Notification component
  ui/src/components/AppBar/Notifications/Notification.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge
