Repository shellhub-io/shellhub, pull requests merged in 2024-08, with the labels that each got.

#4019 feat(gateway): redirect 'DELETE /api/user' to cloud
  gateway/nginx/conf.d/shellhub.conf
Labels: area/gateway

#4018 fix(api): append namespace to the correct array in UserGetInfo
  api/store/mongo/user.go
Labels: area/api

#3999 fix(namespace,api,cli): fixing default announcements
  api/services/namespace.go
  api/services/namespace_test.go
  api/store/mongo/migrations/migration_74.go
  api/store/mongo/migrations/migration_74_test.go
Labels: area/api, go, kind/refactor, area/cli

#4036 fix(ui): increased content padding on premium paywall
  ui/src/components/User/PaywallDialog.vue
Labels: area/ui, javascript, status/good-to-merge

#4037 feat(ui): add premium paywall feature to the session playlist
  ui/src/components/Sessions/SessionList.vue
  ui/src/components/Sessions/SessionPlay.vue
Labels: kind/feature, area/ui, status/ready-for-testing, status/good-to-merge

#4032 fix(api): fix moving session cleanup
  .env
  api/server.go
  api/services/mocks/services.go
  api/services/task.go
  api/services/task_test.go
Labels: area/api, status/needs-review, go

#4040 feat(ui): move the session play button to the new session header recorded
  ui/src/components/Sessions/SessionList.vue
  ui/src/components/Sessions/SessionPlay.vue
  ui/tests/views/__snapshots__/Sessions.spec.ts.snap
Labels: area/ui, status/good-to-merge

#4041 feat(api): Block authentication for users with pending membership status
  api/services/auth.go
  api/services/auth_test.go
Labels: area/api

#4020 refactor(pkg,api,agent): use param as reverse connection path
  pkg/agent/agent.go
  pkg/api/client/client.go
  pkg/api/client/client_public.go
  pkg/api/client/client_public_test.go
  pkg/api/client/mocks/client.go
  pkg/api/client/mocks/reverser.go
  pkg/api/client/reverser.go
  pkg/connman/connman.go
  pkg/httptunnel/httptunnel.go
Labels: area/agent, kind/refactor

#4068 feat(ui): new namespace select
  ui/src/components/Namespace/Namespace.vue
  ui/src/components/Namespace/NamespaceAdd.vue
  ui/src/layouts/AppLayout.vue
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: area/ui, javascript, status/ready-for-testing, status/good-to-merge

#4070 chore(ui): renamed new connection feature to quick connection
  ui/src/components/QuickConnection/QuickConnection.vue
  ui/src/components/QuickConnection/QuickConnectionList.vue
  ui/src/layouts/AppLayout.vue
  ui/tests/components/QuickConnection/QuickConnection.spec.ts
  ui/tests/components/QuickConnection/QuickConnectionList.spec.ts
  ui/tests/components/QuickConnection/__snapshots__/NewConnection.spec.ts.snap
  ui/tests/components/QuickConnection/__snapshots__/NewConnectionList.spec.ts.snap
  ui/tests/components/QuickConnection/__snapshots__/QuickConnection.spec.ts.snap
  ui/tests/components/QuickConnection/__snapshots__/QuickConnectionList.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: area/ui, javascript, status/ready-for-testing

#4090 chore(pkg,api,ssh): correct typos in string literals
  api/pkg/echo/handlers/binder_test.go
  api/pkg/gateway/gateway_test.go
  api/routes/device_test.go
  api/services/api-key_test.go
  api/services/auth_test.go
  api/services/device_tags_test.go
  api/services/device_test.go
  api/services/session_test.go
  api/store/mongo/migrations/migration_9.go
  pkg/agent/agent_test.go
  pkg/api/client/client_public_test.go
  pkg/api/query/paginator_test.go
  ssh/pkg/target/target_test.go
  ssh/server/channels/tcpip.go
  ssh/server/server.go
  ssh/web/errors.go
  ssh/web/session.go
Labels: area/api, area/ssh, go, kind/refactor, area/pkg

#4098 chore(ui)!: generate new openapi version
  ui/src/api/client/api.ts
Labels: area/ui

#4099 fix(ui): rollback namespace member add identifier input to email field
  ui/src/components/Namespace/NamespaceMemberAdd.vue
  ui/src/store/api/namespaces.ts
Labels: kind/feature, area/ui, status/ready-for-testing

#4118 fix(ui): returned namespace add template and buttons
  ui/src/components/Namespace/NamespaceAdd.vue
  ui/src/components/Namespace/NamespaceInstructions.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4119 fix(ui): disable namespace select when user has no namespace
  ui/src/layouts/AppLayout.vue
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4094 feat(agent): use air to reloader and dlv as debugger
  .gitignore
  agent/.air.toml
  agent/Dockerfile
  agent/entrypoint-dev.sh
  agent/refresh.yml
Labels: area/agent, status/good-to-merge

#4066 feat(ui): new breadcrumb router navigation
  ui/src/api/interceptors.ts
  ui/src/components/AppBar/AppBar.vue
  ui/src/components/AppBar/Notifications/Notification.vue
  ui/src/components/AuthMFA/MfaMailRecover.vue
  ui/src/components/Devices/DeviceListChooser.vue
  ui/src/components/Namespace/NamespaceDelete.vue
  ui/src/components/Sessions/SessionList.vue
  ui/src/components/Tables/DeviceTable.vue
  ui/src/router/index.ts
  ui/src/store/helpers/http.ts
  ui/src/views/ConfirmAccount.vue
  ui/src/views/Containers.vue
  ui/src/views/Devices.vue
  ui/src/views/ForgotPassword.vue
  ui/src/views/MfaResetValidation.vue
  ui/src/views/Settings.vue
  ui/src/views/SignUp.vue
  ui/src/views/UpdatePassword.vue
  ui/src/views/ValidationAccount.vue
  ui/tests/components/Containers/__snapshots__/ContainerPendingList.spec.ts.snap
  ui/tests/components/Containers/__snapshots__/ContainerRejectList.spec.ts.snap
  ui/tests/components/Devices/__snapshots__/DevicePendingList.spec.ts.snap
  ui/tests/components/Devices/__snapshots__/DeviceRejectedList.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
  ui/tests/views/UpdatePassword.spec.ts
  ui/tests/views/__snapshots__/Settings.spec.ts.snap
Labels: area/ui, javascript, status/ready-for-testing, status/good-to-merge

#4114 feat(ui): invite namespace member interface
  ui/src/api/interceptors.ts
  ui/src/components/Namespace/NamespaceInviteDialog.vue
  ui/src/components/User/UserWarning.vue
  ui/src/interfaces/INamespace.ts
  ui/src/router/index.ts
  ui/src/store/api/namespaces.ts
  ui/src/store/modules/namespaces.ts
  ui/tests/components/AuthMFA/MfaForceRecoveryMail.spec.ts
  ui/tests/components/Namespace/NamespaceInviteDialog.spec.ts
  ui/tests/components/Namespace/__snapshots__/NamespaceInviteDialog.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, Epic, status/good-to-merge
