Repository shellhub-io/shellhub, pull requests merged in 2024-10, with the labels that each got.

#4194 fix: namespace creation not permitted for user
  api/services/auth.go
  api/services/errors.go
  api/services/namespace.go
  api/services/namespace_test.go
  pkg/models/user.go
Labels: area/api, go, status/require-tests, status/good-to-merge

#4222 fix(ui): resolve type error for v-dialog maxWidth property in TerminalDialog
  ui/src/components/Terminal/TerminalDialog.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4247 refactor(ui): namespace invitation inhanced usability
  ui/src/api/client/api.ts
  ui/src/components/Account/AccountCreated.vue
  ui/src/components/Namespace/NamespaceInviteDialog.vue
  ui/src/components/User/UserWarning.vue
  ui/src/interfaces/INotifications.ts
  ui/src/router/index.ts
  ui/src/store/api/namespaces.ts
  ui/src/store/modules/auth.ts
  ui/src/store/modules/namespaces.ts
  ui/src/views/Login.vue
  ui/src/views/NamespaceInviteCard.vue
  ui/src/views/SignUp.vue
  ui/tests/components/Namespace/NamespaceInviteDialog.spec.ts
  ui/tests/views/Login.spec.ts
  ui/tests/views/NamespaceInviteCard.spec.ts
  ui/tests/views/__snapshots__/Login.spec.ts.snap
  ui/tests/views/__snapshots__/NamespaceInviteCard.spec.ts.snap
  ui/tests/views/__snapshots__/SignUp.spec.ts.snap
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing

#4252 fix(ui): not showing namespace instructions modal
  ui/src/components/User/UserWarning.vue
  ui/src/views/SignUp.vue
Labels: kind/bug, area/ui, javascript

#4265 fix(ui): change the never expiration api key option text
  ui/src/components/Namespace/NamespaceGenerateApiKey.vue
Labels: area/ui, javascript, kind/refactor, status/good-to-merge

#4264 fix(ui): change the text from the namespace member remove modal
  ui/src/components/Namespace/NamespaceMemberDelete.vue
Labels: area/ui, javascript, kind/refactor, status/good-to-merge

#4263 fix(ui): remove username field on namespace member edit
  ui/src/components/Namespace/NamespaceMemberEdit.vue
Labels: kind/bug, area/ui, javascript, kind/refactor, status/good-to-merge
