Repository shellhub-io/shellhub, pull requests merged in 2024-01, with the labels that each got.

#3363 chore(api): rename store files removing sufix `_store`
  api/store/announcement.go
  api/store/device.go
  api/store/device_tags.go
  api/store/firewall.go
  api/store/firewall_tags.go
  api/store/license.go
  api/store/mongo/announcement.go
  api/store/mongo/announcement_test.go
  api/store/mongo/device.go
  api/store/mongo/device_tags.go
  api/store/mongo/device_tags_test.go
  api/store/mongo/device_test.go
  api/store/mongo/firewall.go
  api/store/mongo/firewall_tags.go
  api/store/mongo/firewall_tags_test.go
  api/store/mongo/firewall_test.go
  api/store/mongo/license.go
  api/store/mongo/license_test.go
  api/store/mongo/namespace.go
  api/store/mongo/namespace_test.go
  api/store/mongo/privatekey.go
  api/store/mongo/privatekey_test.go
  api/store/mongo/publickey.go
  api/store/mongo/publickey_tags.go
  api/store/mongo/publickey_tags_test.go
  api/store/mongo/publickey_test.go
  api/store/mongo/session.go
  api/store/mongo/session_test.go
  api/store/mongo/stats.go
  api/store/mongo/stats_test.go
  api/store/mongo/tags.go
  api/store/mongo/tags_test.go
  api/store/mongo/user.go
  api/store/mongo/user_test.go
  api/store/namespace.go
  api/store/privatekey.go
  api/store/publickey.go
  api/store/publickey_tags.go
  api/store/session.go
  api/store/stats.go
  api/store/tags.go
  api/store/user.go
Labels: status/needs-review, status/good-to-merge

#3407 chore(ui): update node dependencies versions
  ui/package-lock.json
  ui/package.json
Labels: area/ui, dependencies, status/good-to-merge

#3408 chore(qa): update node version on QA
  .github/workflows/qa.yml
Labels: area/ci-cd, dependencies

#3401 fix(ui): tag list not reacting to new props
  ui/src/components/Devices/DeviceList.vue
  ui/src/components/Tags/TagFormUpdate.vue
  ui/tests/components/Devices/DeviceList.spec.ts
  ui/tests/components/Devices/__snapshots__/DeviceList.spec.ts.snap
  ui/tests/components/Tags/TagFormUpdate.spec.ts
  ui/tests/components/Tags/__snapshots__/TagFormUpdate.spec.ts.snap
  ui/tests/views/ForgotPassword.spec.ts
  ui/tests/views/__snapshots__/ForgotPassword.spec.ts.snap
Labels: kind/bug, area/ui, javascript, status/ready-for-testing, status/good-to-merge

#3415 fix(ui): profile settings edit tags wrongfully showing not chosen tags
  ui/src/components/Tags/TagEdit.vue
  ui/tests/components/Tags/TagEdit.spec.ts
  ui/tests/components/Tags/__snapshots__/TagEdit.spec.ts.snap
Labels: kind/bug, area/ui, javascript, status/ready-for-testing, status/good-to-merge

#3419 fix(api): return the right error when no resource is matched
  api/store/mongo/user.go
  api/store/mongo/user_test.go
Labels: area/api, status/needs-review

#3423 fix(ssh): init cache to enable web connection work
  ssh/main.go
Labels: status/good-to-merge

#3430 feat(ui): new mfa client generate
  ui/src/api/client/api.ts
  ui/src/components/Setting/SettingProfile.vue
  ui/src/store/modules/auth.ts
  ui/src/views/Login.vue
  ui/tests/components/AuthMFA/MfaDisable.spec.ts
  ui/tests/components/AuthMFA/MfaSettings.spec.ts
  ui/tests/components/Setting/SettingProfile.spec.ts
  ui/tests/store/modules/auth.spec.ts
  ui/tests/views/Login.spec.ts
Labels: kind/feature, area/ui, javascript, status/ready-for-testing

#3443 fix(ui): added margin to qr-code generator on Multi-Factor Authentication
  ui/src/components/AuthMFA/MfaSettings.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#3446 fix(ui): added router guard to redirect mfa url back to login
  ui/src/router/index.ts
Labels: area/ui, javascript, status/good-to-merge

#3452 bump(ui): update vite to 5.0.1
  ui/package-lock.json
  ui/package.json
  ui/src/components/Devices/DeviceChooser.vue
  ui/src/sshpk.js
  ui/src/views/Settings.vue
  ui/vite.config.ts
Labels: area/ui, javascript, dependencies, status/ready-for-testing

#3471 fix(ui): added class to center loading on appLayout
  ui/src/layouts/AppLayout.vue
Labels: kind/bug, area/ui, javascript, status/ready-for-testing

#3472 fix(ui): create store meant to be used only by NewConnection list
  ui/src/components/NewConnection/NewConnection.vue
  ui/src/components/NewConnection/NewConnectionList.vue
  ui/src/store/modules/devices.ts
Labels: kind/bug, area/ui, javascript, status/require-tests

#3473 fix docker compose binary
  bin/add-namespace
  bin/add-user
  bin/add-user-namespace
  bin/cli
  bin/del-namespace
  bin/del-user
  bin/del-user-namespace
  bin/docker-compose
  bin/reset-user-password
  bin/utils
Labels: status/good-to-merge

#3491 feat(ui): mfa recovery login redirect to disabling dialog
  ui/src/components/AuthMFA/RecoveryHelper.vue
  ui/src/components/User/UserWarning.vue
  ui/src/interfaces/INotifications.ts
  ui/src/store/modules/auth.ts
  ui/tests/components/AuthMFA/RecoveryHelper.spec.ts
  ui/tests/components/AuthMFA/__snapshots__/RecoveryHelper.spec.ts.snap
  ui/tests/store/modules/auth.spec.ts
Labels: kind/feature, area/ui, javascript, status/ready-for-testing

#3496 add ';' at the end of the gateway health check return statement
  gateway/conf.d/shellhub.conf
Labels: area/gateway

#3501 fix device update
  api/store/mongo/device.go
Labels: area/api
