Repository shellhub-io/shellhub, pull requests merged in 2024-07, with the labels that each got.

#3957 refactor(api): user detach info
  api/store/mocks/store.go
  api/store/mongo/user.go
  api/store/user.go
  cli/services/users.go
  cli/services/users_test.go
  pkg/models/user.go
Labels: area/api, area/cli, area/pkg, status/good-to-merge

#3968 fix(ui): adjust new user patch endpoint
  ui/src/api/client/api.ts
  ui/src/components/Setting/SettingProfile.vue
  ui/src/interfaces/IUSer.ts
  ui/src/store/api/users.ts
  ui/tests/components/Setting/SettingProfile.spec.ts
Labels: area/ui, javascript, status/ready-for-testing

#3970 fix(gateway): remove GetRole() since is not used on any part of shellhub
  api/pkg/gateway/context.go
  api/pkg/gateway/context_test.go
Labels: do-not-merge, go, kind/refactor, area/gateway

#3986 refactor(api): use with pattern on routes initialization
  api/routes/routes.go
  api/server.go
Labels: do-not-merge

#3979 feat(api): new worker pkg
  agent/go.mod
  agent/go.sum
  api/go.sum
  cli/go.sum
  go.mod
  pkg/worker/asynq/client.go
  pkg/worker/asynq/client_test.go
  pkg/worker/asynq/server.go
  pkg/worker/asynq/server_test.go
  pkg/worker/asynq/task.go
  pkg/worker/asynq/utils.go
  pkg/worker/client.go
  pkg/worker/cron.go
  pkg/worker/errors.go
  pkg/worker/mocks/client.go
  pkg/worker/mocks/server.go
  pkg/worker/server.go
  pkg/worker/task.go
  ssh/go.sum
Labels: area/api, area/pkg

#3972 fix(ui): changed the username error message to a identifier one
  ui/src/components/Namespace/NamespaceMemberAdd.vue
Labels: area/ui, status/good-to-merge

#3996 chore(ssh): remove announcment left spaces
  ssh/session/session.go
Labels: area/ssh

#3960 feat(ui): add a premium paywall to ShellHub community edition
  ui/src/components/User/PaywallDialog.vue
  ui/src/components/User/UserWarning.vue
  ui/src/envVariables.ts
  ui/src/layouts/AppLayout.vue
  ui/src/router/index.ts
  ui/src/store/api/users.ts
  ui/src/store/modules/users.ts
  ui/src/views/FirewallRules.vue
  ui/tests/components/Users/PaywallDialog.ts
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/feature, area/ui, release/breaking-change, status/good-to-merge

#3991 feat(ui): status and date on namespace members listing
  ui/src/components/Namespace/NamespaceMemberList.vue
  ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap
Labels: kind/feature, area/ui, status/ready-for-testing

#3998 fix(ui): increase premium paywall usage through cloud and enterprise features
  ui/src/components/Connector/ConnectorForm.vue
  ui/src/components/Connector/ConnectorList.vue
  ui/src/components/User/PaywallDialog.vue
  ui/src/components/firewall/FirewallRuleAdd.vue
  ui/src/envVariables.ts
  ui/src/views/Connectors.vue
  ui/src/views/FirewallRules.vue
Labels: area/ui, javascript, status/ready-for-testing, status/good-to-merge

#3997 chore(ui): changed logo resolution and coloring
  ui/src/assets/logo-inverted.png
  ui/src/assets/logo.png
Labels: area/ui, status/good-to-merge

#4009 fix(gateway): mfa proxy_pass
  gateway/nginx/conf.d/shellhub.conf
Labels: area/gateway

#4011 chore(gateway): remove useless mfa locations
  gateway/nginx/conf.d/shellhub.conf
Labels: area/gateway

#4010 fix(ui): adjust paywall usage combined with env variables
  ui/src/components/Box/BoxMessage.vue
  ui/src/components/Containers/ContainerList.vue
  ui/src/components/Containers/ContainerPendingList.vue
  ui/src/components/Containers/ContainerRejectedList.vue
  ui/src/components/Tables/DeviceTable.vue
  ui/src/layouts/AppLayout.vue
  ui/src/router/index.ts
  ui/src/views/Containers.vue
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/bug, area/ui, status/ready-for-testing

#4015 fix(ui): new committable directive missing on the device listing
  ui/src/components/Containers/ContainerList.vue
  ui/src/components/Containers/ContainerPendingList.vue
  ui/src/components/Containers/ContainerRejectedList.vue
  ui/src/components/Devices/DeviceList.vue
  ui/src/components/Devices/DevicePendingList.vue
  ui/src/components/Devices/DeviceRejectedList.vue
  ui/src/views/DetailsDevice.vue
  ui/tests/components/Tables/DeviceTable.spec.ts
Labels: kind/bug, area/ui, status/ready-for-testing
