Repository shellhub-io/shellhub, pull requests merged in 2024-11, with the labels that each got.

#4274 feat(ui): new community setup
  bin/setup
  ui/src/api/client/api.ts
  ui/src/api/http.ts
  ui/src/interfaces/IUSer.ts
  ui/src/router/index.ts
  ui/src/store/api/users.ts
  ui/src/store/modules/users.ts
  ui/src/views/Setup.vue
  ui/src/views/UpdatePassword.vue
  ui/tests/layouts/AppLayout.spec.ts
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
  ui/tests/views/Login.spec.ts
  ui/tests/views/Setup.spec.ts
  ui/tests/views/__snapshots__/Setup.spec.ts.snap
  ui/tests/views/__snapshots__/UpdatePassword.spec.ts.snap
Labels: kind/feature, area/ui, javascript, release/breaking-change, status/ready-for-testing, status/good-to-merge

#4291 fix(ui): typos community setup screen
  ui/src/views/Setup.vue
  ui/tests/views/__snapshots__/Setup.spec.ts.snap
Labels: area/ui, javascript, status/good-to-merge

#4301 fix(ui): responsiveness problem in smaller devices on views titles
  ui/src/views/Connectors.vue
  ui/src/views/Containers.vue
  ui/src/views/Devices.vue
  ui/tests/views/__snapshots__/Devices.spec.ts.snap
Labels: kind/bug, area/ui, javascript, status/ready-for-testing

#4300 feat(ui): delete account on cloud instance
  ui/src/components/Namespace/NamespaceInstructions.vue
  ui/src/components/Setting/SettingDrawer.vue
  ui/src/components/Setting/SettingProfile.vue
  ui/src/components/User/UserDelete.vue
  ui/src/components/User/UserWarning.vue
  ui/src/interfaces/INotifications.ts
  ui/src/layouts/AppLayout.vue
  ui/src/store/api/auth.ts
  ui/src/store/modules/auth.ts
  ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
  ui/tests/components/Users/PaywallDialog.spec.ts
  ui/tests/components/Users/UserDelete.spec.ts
  ui/tests/components/Users/__snapshots__/PaywallDialog.spec.ts.snap
  ui/tests/components/Users/__snapshots__/UserDelete.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/feature, javascript, status/good-to-merge

#4320 fix(ui): open version validation
  ui/src/components/Namespace/NamespaceInstructions.vue
Labels: kind/bug, area/ui, status/ready-for-testing, status/good-to-merge

#4325 feat(ui): new help support via chatwoot
  docker-compose.yml
  ui/package-lock.json
  ui/package.json
  ui/src/api/client/api.ts
  ui/src/api/client/base.ts
  ui/src/api/client/common.ts
  ui/src/api/client/configuration.ts
  ui/src/api/client/index.ts
  ui/src/components/AppBar/AppBar.vue
  ui/src/envVariables.ts
  ui/src/main.ts
  ui/src/store/api/namespaces.ts
  ui/src/store/index.ts
  ui/src/store/modules/auth.ts
  ui/src/store/modules/support.ts
  ui/tests/components/AppBar/AppBar.spec.ts
  ui/tests/components/AppBar/__snapshots__/AppBar.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
  ui/tests/store/modules/support.spec.ts
Labels: kind/feature, area/ui, javascript, product/cloud, status/ready-for-testing, Epic, product/enterprise, status/good-to-merge

#4340 feat(namespace): implement functionality to leave a namespace
  diff.patch
  ui/src/api/client/api.ts
  ui/src/authorizer.ts
  ui/src/components/Namespace/NamespaceDelete.vue
  ui/src/components/Namespace/NamespaceLeave.vue
  ui/src/components/Setting/SettingNamespace.vue
  ui/src/interfaces/INotifications.ts
  ui/src/store/api/namespaces.ts
  ui/src/store/modules/namespaces.ts
  ui/tests/components/Namespace/NamespaceLeave.spec.ts
  ui/tests/components/Namespace/__snapshots__/NamespaceLeave.spec.ts.snap
  ui/tests/components/Setting/__snapshots__/SettingNamespace.spec.ts.snap
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, status/good-to-merge

#4336 feat: migration for add field type on namespace
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_82.go
  api/store/mongo/migrations/migration_82_test.go
Labels: worksforme, status/needs-review, Epic, status/good-to-merge

#4341 chore(ui): delete diff patch
  diff.patch
Labels: status/good-to-merge

#4344 feat(ui): update action triggers in lists to use v-btn for consistency
  ui/src/components/Connector/ConnectorList.vue
  ui/src/components/Namespace/NamespaceApiKeyList.vue
  ui/src/components/Namespace/NamespaceMemberList.vue
  ui/src/components/PrivateKeys/PrivateKeyList.vue
  ui/src/components/PublicKeys/PublicKeysList.vue
  ui/src/components/Sessions/SessionList.vue
  ui/src/components/Tables/DeviceTable.vue
  ui/src/components/Tags/TagList.vue
  ui/src/components/firewall/FirewallRuleList.vue
  ui/src/views/ConnectorDetails.vue
  ui/src/views/Connectors.vue
  ui/src/views/DetailsDevice.vue
  ui/src/views/DetailsSessions.vue
  ui/tests/components/Connectors/ConnectorList.spec.ts
  ui/tests/components/Connectors/__snapshots__/ConnectorList.spec.ts.snap
  ui/tests/components/Containers/__snapshots__/ContainerPendingList.spec.ts.snap
  ui/tests/components/Containers/__snapshots__/ContainerRejectList.spec.ts.snap
  ui/tests/components/Devices/__snapshots__/DevicePendingList.spec.ts.snap
  ui/tests/components/Devices/__snapshots__/DeviceRejectedList.spec.ts.snap
  ui/tests/components/Namespace/__snapshots__/NamespaceApiKeyList.spec.ts.snap
  ui/tests/components/PrivateKeys/PrivateKeyList.spec.ts
  ui/tests/components/PublicKeys/PublicKeyList.spec.ts
  ui/tests/components/PublicKeys/__snapshots__/PublicKeyList.spec.ts.snap
  ui/tests/components/Setting/__snapshots__/SettingTags.spec.ts.snap
  ui/tests/components/firewall/FirewallRuleList.spec.ts
  ui/tests/components/firewall/__snapshots__/FirewallRuleList.spec.ts.snap
  ui/tests/views/__snapshots__/DetailsDevice.spec.ts.snap
  ui/tests/views/__snapshots__/DetailsSessions.spec.ts.snap
  ui/tests/views/__snapshots__/FirewallRules.spec.ts.snap
  ui/tests/views/__snapshots__/Sessions.spec.ts.snap
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, status/good-to-merge

#4363 feature(api,ssh,pkg): add events to sessions
  api/routes/routes.go
  api/routes/session.go
  api/services/mocks/services.go
  api/services/session.go
  api/store/mocks/store.go
  api/store/mongo/migrations/main.go
  api/store/mongo/migrations/migration_84.go
  api/store/mongo/migrations/migration_84_test.go
  api/store/mongo/session.go
  api/store/session.go
  pkg/api/internalclient/mocks/internalclient.go
  pkg/api/internalclient/session.go
  pkg/api/requests/session.go
  pkg/models/session.go
  ssh/server/channels/session.go
  ssh/server/channels/tcpip.go
  ssh/session/session.go
Labels: area/api, area/ssh
