Repository shellhub-io/shellhub, pull requests merged in 2025-05, with the labels that each got.

#4771 refactor(ui): replace native DOM event listeners with useEventListener
  ui/src/components/Sessions/Player.vue
  ui/src/components/Setting/SettingBilling.vue
Labels: area/ui, kind/refactor

#4783 feature(install): check logs before confirming agent standalone installation
  install.sh
Labels: status/needs-review

#4800 fix(ui): fix extraneous non-props warning in `TunnelDelete`
  ui/src/components/Tunnels/TunnelDelete.vue
Labels: area/ui

#4803 refactor(ui): remove deprecated `createNewClient` method
  ui/src/api/http.ts
  ui/src/components/AppBar/AppBar.vue
Labels: area/ui, kind/refactor

#4801 fix(ui): replace deprecated `active-color` attribute with `color`
  ui/src/components/Tags/TagSelector.vue
Labels: area/ui

#4805 fix(ui): fix notification list UI
  ui/src/components/AppBar/Notifications/Notification.vue
Labels: area/ui

#4810 fix(ui): limit tunnel custom ttl and add validation to input
  ui/src/components/Tunnels/TunnelCreate.vue
Labels: kind/bug, area/ui

#4819 refactor(ui): fix "perPagae" typo
  ui/admin/src/components/Announcement/AnnouncementList.vue
  ui/admin/src/components/Device/DeviceList.vue
  ui/admin/src/components/FirewallRules/FirewallRulesList.vue
  ui/admin/src/components/Namespace/NamespaceList.vue
  ui/admin/src/components/Sessions/SessionList.vue
  ui/admin/src/components/User/UserList.vue
  ui/admin/tests/unit/views/Announcements/Announcements.spec.ts
  ui/src/components/Connector/ConnectorList.vue
  ui/src/components/Devices/DeviceListChooser.vue
  ui/src/components/PublicKeys/PublicKeysList.vue
  ui/src/components/QuickConnection/QuickConnectionList.vue
  ui/src/components/Sessions/SessionList.vue
  ui/src/components/Tables/DeviceTable.vue
  ui/src/components/Team/ApiKeys/ApiKeyList.vue
  ui/src/components/firewall/FirewallRuleList.vue
Labels: area/ui, javascript, kind/refactor

#4820 fix(ui): improve error handling on device accept action
  ui/src/components/Devices/DeviceActionButton.vue
Labels: kind/bug, area/ui, javascript

#4826 refactor(ui): update SettingTags code
  ui/src/components/Setting/SettingTags.vue
  ui/tests/components/Setting/SettingTags.spec.ts
  ui/tests/components/Setting/__snapshots__/SettingTags.spec.ts.snap
Labels: area/ui

#4827 chore(ui): relocate .v-container styles to Settings view
  ui/src/components/Setting/SettingBilling.vue
  ui/src/components/Setting/SettingNamespace.vue
  ui/src/components/Setting/SettingProfile.vue
  ui/src/views/Settings.vue
  ui/tests/views/__snapshots__/Settings.spec.ts.snap
Labels: area/ui, javascript, kind/refactor, status/good-to-merge

#4829 feat(ui): enhance role selection with descriptions
  ui/src/components/Team/Member/MemberInvite.vue
Labels: kind/feature, area/ui, status/good-to-merge

#4836 fix(ui): add snackbar error for support unsupported env case
  ui/src/components/AppBar/AppBar.vue
Labels: area/ui

#4837 chore(ui): revert calling env.js docker entrypoint
  ui/index.html
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4830 chore(deps): switch asciinema-player to ShellHub hosted version
  ui/package-lock.json
  ui/package.json
Labels: area/ui, status/good-to-merge

#4844 fix(ui): fix typos in UserExport
  ui/admin/src/components/User/UserExport.vue
Labels: kind/bug, area/ui

#4845 fix(ui): fix firewall rules docs URL
  ui/src/views/FirewallRules.vue
Labels: area/ui

#4865 fix(ui): fix field name in TunnelCreate
  ui/src/components/Tunnels/TunnelCreate.vue
Labels: area/ui, javascript
