Repository shellhub-io/shellhub, pull requests merged in 2025-02, with the labels that each got.

#4552 fix(ui): improve terminal dialog behavior and ESC key handling
  ui/src/components/Terminal/TerminalDialog.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4575 fix(ui): improve conditional chatwoot usage
  ui/src/components/AppBar/AppBar.vue
  ui/src/main.ts
Labels: kind/bug, area/ui, javascript, product/cloud, status/ready-for-testing, product/enterprise

#4578 chore(api): use custom log format and level from envs
  api/main.go
Labels: area/api, status/good-to-merge

#4576 refactor(api): connect and create store instance on same function
  api/server.go
  api/store/mongo/store.go
  api/store/mongo/store_test.go
  cli/main.go
Labels: area/api, status/needs-review, area/cli, status/good-to-merge

#4577 chore(api): create default handler to simply server initalization
  api/routes/routes.go
Labels: area/api, status/needs-review, status/good-to-merge

#4584 feat(ui): add paywall check for chat support access
  ui/src/components/AppBar/AppBar.vue
  ui/src/components/User/PaywallChat.vue
  ui/src/main.ts
  ui/src/store/modules/auth.ts
  ui/src/store/modules/support.ts
  ui/tests/components/AppBar/AppBar.spec.ts
  ui/tests/components/AppBar/__snapshots__/AppBar.spec.ts.snap
  ui/tests/components/Users/PaywallChat.spec.ts
  ui/tests/components/Users/__snapshots__/PaywallChat.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
Labels: kind/feature, area/ui, javascript, kind/refactor, status/ready-for-testing

#4603 fix(ui): make namespace settings properties optional
  ui/src/interfaces/INamespace.ts
  ui/src/store/api/namespaces.ts
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4562 refactor(ui): new session play method
  ui/src/api/client/api.ts
  ui/src/api/client/base.ts
  ui/src/api/client/common.ts
  ui/src/api/client/configuration.ts
  ui/src/api/client/index.ts
  ui/src/store/api/sessions.ts
Labels: area/ui, do-not-merge, javascript, kind/refactor, status/ready-for-testing
