Repository shellhub-io/shellhub, pull requests merged in 2025-10, with the labels that each got.

#5296 refactor(ui): migrate web endpoints to new generic dialog
  ui/src/components/WebEndpoints/WebEndpointCreate.vue
  ui/src/components/WebEndpoints/WebEndpointDelete.vue
  ui/tests/components/WebEndpoints/WebEndpointCreate.spec.ts
  ui/tests/components/WebEndpoints/WebEndpointDelete.spec.ts
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing

#5303 refactor(ui): migrate `QuickConnection` to `WindowDialog`
  ui/src/components/QuickConnection/QuickConnection.vue
  ui/src/components/QuickConnection/QuickConnectionList.vue
  ui/tests/components/QuickConnection/__snapshots__/QuickConnectionList.spec.ts.snap
Labels: area/ui, kind/refactor

#5299 fix(ui): add `v-form` to `FormDialog`
  ui/src/components/FormDialog.vue
  ui/tests/components/Connectors/__snapshots__/ConnectorForm.spec.ts.snap
  ui/tests/components/Namespace/__snapshots__/NamespaceEdit.spec.ts.snap
  ui/tests/components/Team/Member/__snapshots__/MemberEdit.spec.ts.snap
  ui/tests/components/Team/Member/__snapshots__/MemberInvite.spec.ts.snap
  ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap
  ui/tests/components/Terminal/__snapshots__/TerminalLoginForm.spec.ts.snap
Labels: area/ui

#5323 fix(ui): stub premium content cards request in `AppLayout`
  ui/tests/layouts/AppLayout.spec.ts
Labels: kind/bug, area/ui
