Repository shellhub-io/shellhub, pull requests merged in 2025-06, with the labels that each got.

#4885 fix(ui): fix player playback time for sessions longer than 24h
  ui/src/components/Sessions/Player.vue
  ui/src/utils/playerPlayback.ts
  ui/tests/components/Sessions/Player.spec.ts
Labels: kind/bug, area/ui, javascript

#4889 refactor(ui): change Connector Add to Container Modal in empty Containers view
  ui/src/views/Containers.vue
Labels: area/ui, kind/refactor, status/good-to-merge

#4888 feat(ui): add tooltip to SessionPlay for not recorded sessions
  ui/src/components/Sessions/SessionList.vue
  ui/src/components/Sessions/SessionPlay.vue
  ui/tests/views/__snapshots__/Sessions.spec.ts.snap
Labels: kind/feature, status/needs-review, javascript, kind/refactor, status/under-testing

#4895 fix(ui): update SessionPlay props in DetailsSessions
  ui/src/views/DetailsSessions.vue
Labels: kind/bug, area/ui

#4867 fix(ui): change namespace add panel using env flag
  ui/src/components/Namespace/NamespaceAdd.vue
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#4908 refactor(ui): refactor admin's NamespaceExport
  ui/admin/src/components/Namespace/NamespaceExport.vue
  ui/admin/src/hooks/namespaceExport.ts
  ui/admin/src/interfaces/IFilter.ts
  ui/admin/tests/unit/views/Namespaces/__snapshots__/index.spec.ts.snap
Labels: area/ui, status/needs-review, kind/refactor

#4927 fix(ui): correct SSH challenge signing with base64 input
  ui/src/components/Terminal/Terminal.vue
  ui/src/utils/crypto.ts
  ui/src/utils/validate.ts
Labels: kind/bug, area/ui, javascript, status/ready-for-testing

#4931 refactor(ui): terminal blob websocket handling
  ui/src/components/Terminal/Terminal.vue
  ui/src/interfaces/ITerminal.ts
  ui/tests/components/Terminal/Terminal.spec.ts
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing, status/good-to-merge

#4942 feat(ui): add loading state to Play Session button
  ui/src/components/Sessions/SessionPlay.vue
Labels: area/ui

#4935 fix(ui): fix quick connection card min-height
  ui/src/components/QuickConnection/QuickConnection.vue
Labels: area/ui
