Repository shellhub-io/shellhub, pull requests merged in 2025-01, with the labels that each got.

#4447 refactor(api): simplifying geoip initialization
  api/server.go
Labels: status/needs-review

#4504 feat(ui): add TTL support and expiration management
  ui/src/api/client/api.ts
  ui/src/components/Tunnels/TunnelCreate.vue
  ui/src/components/Tunnels/TunnelList.vue
  ui/src/interfaces/ITunnel.ts
  ui/src/store/api/tunnels.ts
  ui/src/store/modules/tunnels.ts
  ui/tests/components/Tunnels/TunnelCreate.spec.ts
  ui/tests/components/Tunnels/TunnelList.spec.ts
  ui/tests/components/Tunnels/__snapshots__/TunnelList.spec.ts.snap
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, status/good-to-merge

#4520 feat(ui): enhance tunnel creation and list functionalities
  ui/src/components/Tunnels/TunnelCreate.vue
  ui/src/components/Tunnels/TunnelList.vue
Labels: kind/feature, area/ui, status/ready-for-testing, status/good-to-merge

#4518 feat(ui): implement SAML SSO Configuration for enterprise instance
  ui/src/api/client/api.ts
  ui/src/components/Setting/SettingProfile.vue
  ui/src/layouts/AppLayout.vue
  ui/src/store/api/users.ts
  ui/src/store/modules/auth.ts
  ui/src/store/modules/users.ts
  ui/src/views/Login.vue
  ui/tests/components/Setting/SettingProfile.spec.ts
  ui/tests/components/Setting/__snapshots__/SettingProfile.spec.ts.snap
  ui/tests/layouts/__snapshots__/AppLayout.spec.ts.snap
  ui/tests/views/Login.spec.ts
  ui/tests/views/__snapshots__/Login.spec.ts.snap
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, product/enterprise, status/good-to-merge

#4528 refactor(ui): add custom timeout option for tunnel creation
  ui/src/components/Tunnels/TunnelCreate.vue
  ui/tests/components/Tunnels/TunnelCreate.spec.ts
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing, status/good-to-merge

#4538 feat(ui): auto-open terminal on specific route
  ui/src/components/Terminal/TerminalDialog.vue
  ui/src/router/index.ts
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, status/good-to-merge

#4539 feat(ui): close dialog on Escape key press
  ui/src/components/Terminal/TerminalDialog.vue
Labels: kind/feature, area/ui, product/cloud, status/good-to-merge
