Repository shellhub-io/shellhub, pull requests merged in 2025-08, with the labels that each got.

#5112 feat(ui): implement Web Endpoints feature to replace legacy Tunnel system
  ui/src/api/client/api.ts
  ui/src/api/http.ts
  ui/src/authorizer.ts
  ui/src/components/Tunnels/TunnelList.vue
  ui/src/components/WebEndpoints/WebEndpointCreate.vue
  ui/src/components/WebEndpoints/WebEndpointDelete.vue
  ui/src/components/WebEndpoints/WebEndpointList.vue
  ui/src/envVariables.ts
  ui/src/interfaces/IWebEndpoints.ts
  ui/src/layouts/AppLayout.vue
  ui/src/router/index.ts
  ui/src/store/api/tunnels.ts
  ui/src/store/api/web_endpoints.ts
  ui/src/store/index.ts
  ui/src/store/modules/tunnels.ts
  ui/src/store/modules/web_endpoints.ts
  ui/src/views/DetailsDevice.vue
  ui/src/views/WebEndpoints.vue
  ui/tests/components/Tunnels/TunnelCreate.spec.ts
  ui/tests/components/Tunnels/TunnelDelete.spec.ts
  ui/tests/components/Tunnels/TunnelList.spec.ts
  ui/tests/components/WebEndpoints/WebEndpointCreate.spec.ts
  ui/tests/components/WebEndpoints/WebEndpointDelete.spec.ts
  ui/tests/components/WebEndpoints/WebEndpointList.spec.ts
  ui/tests/components/WebEndpoints/__snapshots__/TunnelCreate.spec.ts.snap
  ui/tests/components/WebEndpoints/__snapshots__/TunnelDelete.spec.ts.snap
  ui/tests/components/WebEndpoints/__snapshots__/TunnelList.spec.ts.snap
  ui/tests/components/WebEndpoints/__snapshots__/WebEndpointsCreate.spec.ts.snap
  ui/tests/store/modules/web_endpoints.spec.ts
  ui/tests/views/WebEndpoints.spec.ts
  ui/tests/views/__snapshots__/DetailsDevice.spec.ts.snap
Labels: kind/feature, area/ui, status/ready-for-testing

#5117 fix(ui): show beta chip for cloud-only beta nav items
  ui/src/layouts/AppLayout.vue
  ui/tests/layouts/AppLayout.spec.ts
Labels: area/ui, status/ready-for-testing, status/good-to-merge

#5123 fix(ui): fix active and action selects in `FirewallRuleAdd`
  ui/src/components/firewall/FirewallRuleAdd.vue
Labels: kind/bug, area/ui

#5170 chore(ui): update OpenAPI specification
  ui/src/api/client/api.ts
  ui/src/api/client/base.ts
  ui/src/api/client/common.ts
  ui/src/api/client/configuration.ts
  ui/src/api/client/index.ts
  ui/src/store/api/firewall_rules.ts
Labels: area/ui, product/cloud, openapi
