Repository shellhub-io/shellhub, pull requests merged in 2025-04, with the labels that each got.

#4704 fix(ui): fix punycode warnings
  ui/package-lock.json
  ui/package.json
Labels: area/ui

#4693 feat(ui): add invite link generation for adding new namespace member
  ui/src/api/client/api.ts
  ui/src/components/Team/Member/MemberInvite.vue
  ui/src/interfaces/INotifications.ts
  ui/src/store/api/namespaces.ts
  ui/src/store/modules/namespaces.ts
  ui/tests/components/Team/Member/MemberInvite.spec.ts
Labels: kind/feature, area/ui, javascript, status/ready-for-testing, status/good-to-merge, status/under-testing

#4723 refactor(ui): simplify license upload input logic
  ui/admin/src/components/Settings/SettingsLicense.vue
  ui/admin/src/store/modules/license.ts
  ui/admin/src/views/License.vue
  ui/admin/tests/unit/components/License/License/__snapshots__/index.spec.ts.snap
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing, status/good-to-merge

#4721 refactor(ui): centralize layout handling and simplify auth check
  ui/admin/src/App.vue
  ui/admin/src/layouts/AppLayout.vue
  ui/admin/src/layouts/SimpleLayout.vue
  ui/admin/src/router/index.ts
  ui/admin/src/store/modules/auth.ts
  ui/admin/src/store/modules/license.ts
  ui/admin/tests/unit/store/modules/Auth.spec.ts
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing, product/enterprise

#4724 fix(api): remove api key blocking to missing routes
  api/routes/routes.go
Labels: status/needs-review

#4756 refactor(ui): improve SSO toggle logic and UI rendering
  ui/admin/src/components/Instance/SSO/ConfigureSSO.vue
  ui/admin/src/components/Settings/SettingsAuthentication.vue
  ui/admin/tests/unit/components/Settings/SettingsAuthentication/__snapshots__/index.spec.ts.snap
Labels: area/ui, kind/refactor, status/ready-for-testing, product/enterprise

#4755 refactor(ui): streamline dialog structure and inputs
  ui/src/components/QuickConnection/QuickConnection.vue
  ui/src/components/QuickConnection/QuickConnectionList.vue
  ui/tests/components/QuickConnection/QuickConnection.spec.ts
Labels: area/ui, kind/refactor, status/good-to-merge
