Repository shellhub-io/shellhub, pull requests merged in 2025-09, with the labels that each got.

#5202 fix(ui): ensure name is loaded before MFA recovery and reset
  ui/src/store/modules/auth.ts
Labels: kind/bug, area/ui, javascript, status/good-to-merge

#5231 fix(api,ssh): update script that generate private keys in pkcs8 format
  Makefile
  api/entrypoint-dev.sh
  devscripts/add-device
  ssh/entrypoint-dev.sh
Labels: status/good-to-merge

#5250 fix(ui): align Device & FirewallRules tests with tag objects
  ui/admin/tests/unit/views/Device/__snapshots__/index.spec.ts.snap
  ui/admin/tests/unit/views/Device/index.spec.ts
  ui/admin/tests/unit/views/FirewallRules/__snapshots__/index.spec.ts.snap
  ui/admin/tests/unit/views/FirewallRules/index.spec.ts
Labels: area/ui, status/good-to-merge

#5253 fix(ui): persist filters and sorting in several admin stores
  ui/admin/src/components/Device/DeviceList.vue
  ui/admin/src/components/Namespace/NamespaceList.vue
  ui/admin/src/components/User/UserList.vue
  ui/admin/src/store/modules/devices.ts
  ui/admin/src/store/modules/namespaces.ts
  ui/admin/src/store/modules/users.ts
  ui/admin/src/views/Device.vue
  ui/admin/src/views/Namespaces.vue
  ui/admin/src/views/Users.vue
Labels: kind/bug, area/ui, status/ready-for-testing, product/enterprise

#5264 fix(ui): start layout state in store as an empty value
  ui/src/App.vue
  ui/src/store/modules/layout.ts
  ui/tests/store/modules/layout.spec.ts
Labels: kind/bug, area/ui

#5268 fix(ui): fix Terminal Dialog
  ui/src/components/Terminal/TerminalDialog.vue
  ui/tests/components/Terminal/__snapshots__/TerminalDialog.spec.ts.snap
Labels: kind/bug, area/ui

#5171 chore: unify agent multi-architecture Dockerfiles and simplify build workflow
  .github/workflows/build-agent.yml
  agent/Dockerfile
  agent/Dockerfile.amd64
  agent/Dockerfile.arm32v6
  agent/Dockerfile.arm32v7
  agent/Dockerfile.arm64v8
  agent/Dockerfile.i386
Labels: do-not-merge

#5272 refactor(ui): unify dialogs using new shared dialog components
  ui/src/components/PrivateKeys/PrivateKeyAdd.vue
  ui/src/components/PrivateKeys/PrivateKeyDelete.vue
  ui/src/components/PrivateKeys/PrivateKeyEdit.vue
  ui/src/components/PublicKeys/PublicKeyAdd.vue
  ui/src/components/PublicKeys/PublicKeyDelete.vue
  ui/src/components/PublicKeys/PublicKeyEdit.vue
  ui/src/components/firewall/FirewallRuleAdd.vue
  ui/src/components/firewall/FirewallRuleDelete.vue
  ui/src/components/firewall/FirewallRuleEdit.vue
  ui/tests/components/PrivateKeys/PrivateKeyAdd.spec.ts
  ui/tests/components/PrivateKeys/PrivateKeyDelete.spec.ts
  ui/tests/components/PrivateKeys/__snapshots__/PrivateKeyEdit.spec.ts.snap
  ui/tests/components/PublicKeys/PublicKeyAdd.spec.ts
  ui/tests/components/PublicKeys/PublicKeyDelete.spec.ts
  ui/tests/components/PublicKeys/PublicKeyEdit.spec.ts
  ui/tests/components/PublicKeys/__snapshots__/PublicKeyEdit.spec.ts.snap
  ui/tests/components/firewall/FirewallRuleAdd.spec.ts
  ui/tests/components/firewall/FirewallRuleDelete.spec.ts
  ui/tests/components/firewall/FirewallRuleEdit.spec.ts
Labels: area/ui, javascript, product/cloud, kind/refactor, status/ready-for-testing

#5276 chore(ci): add Build action for UI
  .github/workflows/qa.yml
Labels: area/ui, area/ci-cd, github_actions

#5275 fix(ui): correct types and expose errors in dialog refactor
  ui/src/components/PublicKeys/PublicKeyAdd.vue
  ui/src/components/PublicKeys/PublicKeyEdit.vue
  ui/src/components/firewall/FirewallRuleAdd.vue
  ui/tests/components/PublicKeys/PublicKeyAdd.spec.ts
  ui/tests/components/PublicKeys/PublicKeyDelete.spec.ts
  ui/tests/components/PublicKeys/PublicKeyEdit.spec.ts
Labels: kind/bug, area/ui, status/work-in-progress, status/needs-review, javascript

#5286 refactor(ui): replace BaseDialog with FormDialog/MessageDialog in tags
  ui/src/components/Tags/TagCreate.vue
  ui/src/components/Tags/TagEdit.vue
  ui/src/components/Tags/TagFormUpdate.vue
  ui/src/components/Tags/TagRemove.vue
  ui/tests/components/Tags/TagCreate.spec.ts
  ui/tests/components/Tags/TagFormUpdate.spec.ts
  ui/tests/components/Tags/TagRemove.spec.ts
Labels: area/ui, javascript, kind/refactor, status/ready-for-testing
