Repository shellhub-io/shellhub, pull requests merged in 2025-03, with the labels that each got.

#4640 fix(ui): fix Vue's attribute inheritance warnings
  ui/src/components/AppBar/AppBar.vue
  ui/src/components/Namespace/Namespace.vue
  ui/src/components/User/UserWarning.vue
Labels: area/ui

#4643 fix(ui): declare useChatwoot on auth store only when it will be used
  ui/src/store/modules/auth.ts
Labels: kind/bug, area/ui, javascript

#4646 fix(ui): stub global fetch, clean up mock setup, and improve async handling
  ui/tests/components/Users/PaywallDialog.spec.ts
Labels: area/ui, javascript, status/good-to-merge

#4671 fix(ui): fix `getSessionRecord` error
  ui/src/store/api/users.ts
Labels: area/ui

#4688 refactor(api): use websocket connection to receive events from SSH session
  api/routes/handler.go
  api/routes/healthcheck_test.go
  api/routes/routes.go
  api/routes/session.go
  api/routes/session_test.go
  pkg/api/internalclient/mocks/internalclient.go
  pkg/api/internalclient/session.go
  pkg/api/requests/session.go
  pkg/websocket/mocks/conn.go
  pkg/websocket/mocks/upgrader.go
  pkg/websocket/utils.go
  pkg/websocket/websocket.go
  ssh/session/session.go
Labels: area/api, area/ssh
