Repository shellhub-io/shellhub, pull requests merged in 2025-07, with the labels that each got.

#4965 fix(ui): restore resize handling during incomplete signature
  ui/src/components/Terminal/Terminal.vue
Labels: kind/bug, area/ui, javascript, status/ready-for-testing

#4973 refactor(ui): remove redundant `isReady` ref in Terminal component
  ui/src/components/Terminal/Terminal.vue
  ui/tests/components/Terminal/Terminal.spec.ts
Labels: area/ui, kind/refactor

#4971 fix(ui): fit terminal before opening WebSocket connection
  ui/src/components/Terminal/Terminal.vue
Labels: kind/bug, area/ui, javascript

#4980 fix(ui): correct copy icon behavior in command field
  ui/src/components/Terminal/TerminalHelper.vue
Labels: area/ui, status/good-to-merge

#4981 fix(ui): fix NamespaceEdit error when changing max devices number
  ui/admin/src/components/Namespace/NamespaceEdit.vue
Labels: kind/bug, area/ui

#4982 chore(ui): remove unused Public Key interface, store and tests in admin
  ui/admin/src/interfaces/IPublicKey.ts
  ui/admin/src/store/api/public_keys.ts
  ui/admin/src/store/modules/public_keys.ts
  ui/admin/tests/unit/store/modules/public_keys.spec.ts
Labels: area/ui, product/enterprise

#4994 refactor(ui): refactor firewall rule add and edit dialogs
  ui/admin/tests/unit/components/FirewallRules/FirewallRulesList/index.spec.ts
  ui/src/components/firewall/FirewallRuleAdd.vue
  ui/src/components/firewall/FirewallRuleEdit.vue
  ui/src/components/firewall/FirewallRuleList.vue
  ui/src/interfaces/IFilter.ts
  ui/src/store/api/firewall_rules.ts
  ui/tests/components/firewall/FirewallRuleAdd.spec.ts
  ui/tests/components/firewall/FirewallRuleEdit.spec.ts
  ui/tests/components/firewall/__snapshots__/FirewallRuleAdd.spec.ts.snap
  ui/tests/components/firewall/__snapshots__/FirewallRuleList.spec.ts.snap
  ui/tests/views/__snapshots__/FirewallRules.spec.ts.snap
Labels: area/ui, product/cloud, kind/refactor, status/ready-for-testing

#4991 fix(ui): validation for X.509 certificate in SAML config
  ui/admin/src/components/Instance/SSO/ConfigureSSO.vue
  ui/admin/tests/unit/components/Instance/SSO/index.spec.ts
  ui/src/utils/crypto.ts
  ui/src/utils/validate.ts
Labels: kind/bug, area/ui, status/needs-review, javascript, status/ready-for-testing, product/enterprise

#5014 fix(ui): fix member's role case when inviting with link
  ui/src/components/Team/Member/MemberInvite.vue
Labels: kind/bug, area/ui

#5016 fix(ssh): resolve terminal dimension limitations by aligning with RFC 4254
  ssh/web/session.go
  ssh/web/utils.go
  ssh/web/websocket.go
  ssh/web/websocket_test.go
Labels: do-not-merge
